### ISSUE TITLE
UI elements are not showing localized strings

### ISSUE THREAD

**Issue by Filipsi** [Prospector/ModMenu#1]
**Issue description**
Buttons and labels added by ModMenu are showing unlocalized string for en_us language.

**Versions**
Java: 1.8.0_192
Mod version: 1.1.0-15
Fabric version: 18w50a.73-0.3.0.77
Log: [QbvTyr3R](https://pastebin.com/raw/QbvTyr3R)

**Screenshots**
![mainmenu](https://user-images.githubusercontent.com/5103404/50525634-f621bd80-0adc-11e9-970f-48a70b178ea1.png)
![modlist](https://user-images.githubusercontent.com/5103404/50525637-fc179e80-0adc-11e9-8bef-a6e73b5683d2.png)

**Comment by vertex101** [comment]
the reason is you dont have Fabric API installed as it says 

https://i.imgur.com/qMWZaQg.png

**Comment by Prospector** [comment]
Ah yes. Technically the mod works without Fabric API but you do require it for the mod icons to load and for localization.
