### ISSUE TITLE
Use mod.json "icon" field

### ISSUE THREAD

**Issue by sargunv** [Prospector/ModMenu#10]
The [mod.json spec](https://fabricmc.net/wiki/format:modjson) includes an "icon" field. Would it be possible to use that to get the path to the mod's icon, instead of requiring exactly "modid/icon.png"?

I'd be happy to make the PR myself if this is something that would be accepted.

**Comment by Prospector** [comment]
Yeah, feel free to make the PR. As long as the current path is still there as a fallback.

**Comment by sargunv** [comment]
I just took a look; unfortunately it looks like the icon field is never read into the [ModInfo class](https://github.com/FabricMC/fabric-loader/blob/master/src/main/java/net/fabricmc/loader/ModInfo.java) despite being documented in [the wiki](https://fabricmc.net/wiki/format:modjson).

**Comment by Prospector** [comment]
Looks like when Loader 0.4 is released, this will be available in the ModMetadata https://github.com/FabricMC/fabric-loader/blob/dev/0.4/src/main/java/net/fabricmc/loader/api/metadata/ModMetadata.java#L62

**Comment by sargunv** [comment]
Cool, I'll make the PR when that's released (or you could do it)

**Comment by Prospector** [comment]
Mod Menu 1.2.1 uses this
