### ISSUE TITLE
Virus Detected

### ISSUE THREAD

**Issue by BigChin** [Prospector/ModMenu#104]
Mod Menu currently seems to tell me that all my mods have been checked and found to be in the clear by McAfee antivirus… except for Mod Menu itself. I don’t remember this being there before, but maybe I just didn’t notice. Also not sure where it gets the checks from. No McAfee running locally and I don’t see any checks on the Files tab here. Is the self-quarantine driving me crazy?
(https://www.curseforge.com/minecraft/mc-mods/modmenu)
-Freso

Mod Menu showing "Virus Detected" for me aswell.
(https://imgur.com/a/mOkfqMS)

**Comment by Vresod** [comment]
I think it's an April Fools Day prank.

**Comment by 0xfeeddeadbeef** [comment]
70 anti-viruses also think it's an April Fools prank: https://www.virustotal.com/gui/file/c8137dd049ed48a106ff8f32235969c763dd21b8acda8a8775cef31e0a4868f3/detection

**Comment by Vresod** [comment]
What's odd is that I can't find any references to April, virus, or the number 4 in the code. Another project that did an April Fools Day prank (roughly enough items) had easy to find code.

**Comment by Vresod** [comment]
[BadgeRenderer.java](https://github.com/Prospector/ModMenu/blob/1.15/src/main/java/io/github/prospector/modmenu/util/BadgeRenderer.java#L45) contains something related to the calendar but I can't seem to get April 1st out of any of the numbers.

**Comment by Linguardium** [comment]
good catch. if we start an array at 0, then 0b11 = 3 or the 4th entry in the array
so assuming that line gives 
if (Calendar.getInstance().get(0b10) == 0b11 && Calendar.getInstance().get(0b101) == 0x1) {
if (month == 4 && day == 1) {

**Comment by Prospector** [comment]
:)

**Comment by DarianLStephens** [comment]
I recently encountered this same thing, and while I realized after some time that it was an April Fools thing, this seems a bit much for one.

Maybe it would be better if it _wasn't_ an actual antivirus thing?
Something like 'McReeper Security' instead of 'McAfee'?

**Comment by Jeropeesee-Bashan** [comment]
Guys, it seems I got trolled too...

**Comment by srnyx** [comment]
> Guys, it seems I got trolled too...

Same... except I had sorta known it was a prank.
I had only been skeptical cause earlier I was dealing with malware that was sent to me on Discord so I was on alert lmao, scared me a bit.
Not gonna lie though, I love the green, it looks super nice with the menu

**Comment by fchagas97** [comment]
I just got trolled by mojang too lol

**Comment by vakiliner** [comment]
I also noticed this sign, but I asked myself a different question: not "Why is it considered a virus?", but "Since when have I installed an antivirus?", and this happened just at the moment when I was downloading optimization mods, I thought that this antivirus was in one of the downloaded mods.

**Comment by DarianLStephens** [comment]
Heh, it begins as it does every year.
