### ISSUE TITLE
Game versions don't include Fabric

### ISSUE THREAD

**Issue by magneticflux-** [Prospector/ModMenu#107]
The last few releases don't include `Fabric` as a game version:
- https://www.curseforge.com/minecraft/mc-mods/modmenu/files/2877865
- https://www.curseforge.com/minecraft/mc-mods/modmenu/files/2878341
- https://www.curseforge.com/minecraft/mc-mods/modmenu/files/2899704
- https://www.curseforge.com/minecraft/mc-mods/modmenu/files/2902148

The last release that does is here:
- https://www.curseforge.com/minecraft/mc-mods/modmenu/files/2877779

This causes issues with mod managers that expect Fabric mods.

**Comment by MagmaSlime123** [comment]
They wont answer. This is a dead project.

**Comment by Prospector** [comment]
I apologize for the delay. The 1.16 branch needs some refactors to get its publishing system up to par with the 1.15 branch. Once I do that, the issue will be fixed.

**Comment by Prospector** [comment]
Did a quick fix on this
