### ISSUE TITLE
[20w17a] Crash with mouse wheelie

### ISSUE THREAD

**Issue by supersaiyansubtlety** [Prospector/ModMenu#109]
My game crashes on startup when I have both this and [mouse wheelie](https://www.curseforge.com/minecraft/mc-mods/mouse-wheelie) are install on 20w17a. 
It works fine if I remove either mod. 
[crash-2020-04-23_16.05.44-client.txt](https://github.com/Prospector/ModMenu/files/4525757/crash-2020-04-23_16.05.44-client.txt)

[Link to issue](https://github.com/Siphalor/mouse-wheelie/issues/61) on Mouse Wheelie repo

**Comment by Prospector** [comment]
It looks like Mouse Wheelie has their Mod Menu support excluded from the latest version but they didn't take it out of their mod metadata, so Mod Menu still tries to load it. https://github.com/Siphalor/mouse-wheelie/blob/1.16/build.gradle#L78

This would be on them to fix
