### ISSUE TITLE
Multiplayer support

### ISSUE THREAD

**Issue by roninvanderwerke** [Prospector/ModMenu#111]
It would be really cool for this mod to add server support. Since now there is no way that I know off how you could find the active mods except from testing every mod manually. A /mod(s)(list) command would be awesome.

**Comment by Madis0** [comment]
I'd say it is up to the servers to advertise what mods they are using, if they expect the clients to use them too.

**Comment by roninvanderwerke** [comment]
I agree, however I meant this from the server admin perspective. As of now there's no way, that I know of, that shows which mods are properly installed.

**Comment by Prospector** [comment]
When you start the server the list is printed out to the log by Fabric Loader. That should be good enough I think?

**Comment by Prospector** [comment]
Gonna go ahead and say this is out of scope. Mod Menu's scope is clientside only.
