### ISSUE TITLE
Fix non-mod JVM libraries displaying as mods (not as libraries)

### ISSUE THREAD

**Issue by prc94** [Prospector/ModMenu#113]
Screenshots of what i talking about
https://imgur.com/a/Qau1JaL

**Comment by Prospector** [comment]
Nothing I can do about this, they need the `"modmenu:api": true` custom element in their metadata

**Comment by prc94** [comment]
Isn't it possible to somehow determine that it is not even a mod?

**Comment by Prospector** [comment]
Not really, some sort of identifying metadata would have to be added via fabric loom.

**Comment by prc94** [comment]
But why not just check for presence of fabric.mod.json file? or it is not possible?

**Comment by Prospector** [comment]
When a mod packages a library like that it means it has a fabric.mod.json. Loom makes them mods. Anything that isn't a mod wouldn't show up in Mod Menu.
