### ISSUE TITLE
Pressing esc in the Mod Menu

### ISSUE THREAD

**Issue by MMK21Hub** [Prospector/ModMenu#119]
(In 1.15 at least) pressing `esc` while in a submenu takes you into the previous menu. However, the Mod Menu does not follow this behaviour. Easiest to see when in a world.

1. Join a singleplayer world
2. Pause the game, and open the Mod Menu.
21. Press `esc`.
❌: The game unpauses.

**What I expected:** The game would return to the Pause Menu.

**Comment by galfar-coder** [comment]
yeah thats kinda to be fixed, i think, its anyoning for me.

**Comment by Prospector** [comment]
Vanilla's screens don't do this consistently, however. Some take you back 1 step, some take you all the way back. Not sure what I should do here.

**Comment by Sollace** [comment]
I think the intended behaviour from Mojang is for all screens to just go back to the previous. I can't remember if I've changed this for MineLP and HDSkins' screens yet...

**Comment by NeusFear** [comment]
I think going back one screen is better, it's easier to hit escape multiple times when your finger is already on the key than it is to move the mouse around to get back to where you were.

**Comment by MMK21Hub** [comment]
Related bugs:
- https://bugs.mojang.com/browse/MC-94491
- https://bugs.mojang.com/browse/MC-122135
- https://bugs.mojang.com/browse/MC-122495
- https://bugs.mojang.com/browse/MC-182909
- https://bugs.mojang.com/browse/MC-125104

**Comment by MMK21Hub** [comment]
Thanks for fixing! (b3fa63539eab2c7e5df61ca49b5145cd196bdbca https://www.curseforge.com/minecraft/mc-mods/modmenu/files/3006339)

**Comment by Prospector** [comment]
np
