### ISSUE TITLE
[CRASH] Crash when clicking mods button

### ISSUE THREAD

**Issue by Kore-Development** [Prospector/ModMenu#12]
[https://paste.ee/p/z7eej](https://paste.ee/p/z7eej)

**Comment by Kore-Development** [comment]
I also put this as a comment on Curseforge

**Comment by Prospector** [comment]
You're on a very outdated version of ModMenu for 19w12b

**Comment by Prospector** [comment]
Wait, that's the version bug. Try with the latest version anyway and let me know if it still happens

**Comment by Kore-Development** [comment]
https://minecraft.curseforge.com/projects/modmenu/files/2695247

**Comment by Prospector** [comment]
Update to the latest
