### ISSUE TITLE
Startup crash with 1.12.0+build.14 "java.lang.NullPointerException: Initializing game"

### ISSUE THREAD

**Issue by Danklor** [Prospector/ModMenu#120]
Using previous version 1.11.8+build.13 works fine, but the latest release crashes every startup with the attached log.
[crash-2020-06-09_10.34.14-client.txt](https://github.com/Prospector/ModMenu/files/4752865/crash-2020-06-09_10.34.14-client.txt)

**Comment by jackmawer** [comment]
Also facing the same issue on 1.16-pre2. Rolling back to build 13 works for the time being.

**Comment by Prospector** [comment]
My apologies, I forgot to remove some WIP code I started adding but decided to wait on.

**Comment by Prospector** [comment]
I've fixed this in 1.12.1
