### ISSUE TITLE
Issues with Tweeds' config screens

### ISSUE THREAD

**Issue by Siphalor** [Prospector/ModMenu#124]
> This happens with Tweed's ModMenu entry **only when a world is open**.
> 
> When the user clicks to select the entry in ModMenu the config opens instantly and cannot be closed easily.
>
> I don't know why this happens but I would suspect that this happens because I provide both the screen as direct mod screen but also through the library-provider. As such I would claim that this is a fault on ModMenu's end.

See Siphalor/tweed-api#8

Edit:
An easy way to reproduce is to download the latest Mouse Wheelie release for MC 1.16.1.
Then enter a world escape and open the mod menu.
Click on the entry for Tweed (might have to toggle view libraries first) and enjoy the trap that you're in then. 
Like Madis noted the only way to have a chance to exit is to hold escape :)

**Comment by Prospector** [comment]
Why would your screen be reopened? Mod Menu only ever does that when you click the button.

**Comment by Siphalor** [comment]
I did some debugging:

When rendering a config screen you call [`ModMenu#hasConfigScreenFactory`](https://github.com/Prospector/ModMenu/blob/1.16/src/main/java/io/github/prospector/modmenu/ModMenu.java#L40-L42).

Inside of this function, for whatever reason, you call the `create` of the screen handler.

Tweed's default create function **has side effects**. In fact if the player is in a world it will return a wait screen and send a packet to the server requesting the server configuration. When that packet arrives Tweed will open the configuration screen on it's own.

I never thought anything bad about that because it's totally undocumented that the `create` handler can randomly get called.

There are two ways out of this:
1. Get rid of calls to `create` when it's not meant to create a screen.
2. Document that the `create` function shouldn't have any side effects. And then I'm gonna have to hack something together to get Tweed working the way it should.

**Comment by Prospector** [comment]
Well, I need to be able to create a screen in order to tell if it exists and if button should be enabled or not. Hmm. IMO you shouldn't be opening a screen just based on data being sent. Could the data be cached somewhere and only accessed when the screen opens naturally?

**Comment by Siphalor** [comment]
It probably could.

I would then need to to extend vanilla's `NoticeScreen` that I'm currently using and build some stuff around it.

Can't you just define that all mods that don't declare screen factories for other mods will have to provide a config screen?

Also a bit unrelated: Currently a config library can't provide a config screen for itself using the id-to-screen-factory map. It always needs to override the other, normal method as well.

**Comment by Prospector** [comment]
I think this was resolved on Tweed's end
