### ISSUE TITLE
Hint text for drag and drop

### ISSUE THREAD

**Issue by Madis0** [Prospector/ModMenu#130]
Mod Menu added a drag and drop feature, but it is not visible or obvious to the user, so I would suggest a hint text similar to the vanilla one.
![2020-07-11_12 29 15](https://user-images.githubusercontent.com/8611110/87221111-4b958680-c372-11ea-82d1-2f70770e12d4.png)

**Comment by Prospector** [comment]
tbh, I'm not sure where it would go. Mod Menu already has very high information density.

**Comment by Madis0** [comment]
I would suggest on the right of the searchbox, on top of mod title/description. Since it is grayed out, I think it wouldn't be too distracting.

**Comment by Madis0** [comment]
e3cb95fcc096c75eb517fff10c85
