### ISSUE TITLE
Better client-side mod detection

### ISSUE THREAD

**Issue by juliand665** [Prospector/ModMenu#134]
Currently, the only way to have mod menu show a mod as client-side is to add the `modmenu:clientsideOnly` tag to fabric.mod.json. However, client-side-only mods _should_ already be using `"environment": "client"` so as to not load on dedicated servers. It seems like a no-brainer to have mod menu simply detect that rather than requiring mods to add a custom tag (you can keep the tag of course, this request is simply additive).

**Comment by Prospector** [comment]
Unfortunately, there's nothing I can do from my end without accessing Fabric Loader internals. For some reason, the environment type is not exposed in Loader's API. I've been meaning to make a Loader PR at some point but never did get around to it.

**Comment by juliand665** [comment]
Thanks so much for this! Love the work you're doing <3

**Comment by Prospector** [comment]
np
