### ISSUE TITLE
Realms icon with incorrect offset

### ISSUE THREAD

**Issue by Boobies** [Prospector/ModMenu#138]
I don't know whether I should be reporting this to Mod Menu or Replay Mod but the fact is I have both and they both add a button to the game's main menu. The diamond shape that normally appears on the right of the Realms button now does not appear on that button but is offset on the screen somewhere.

**Comment by Prospector** [comment]
Could you send a screenshot please? And what versions are you using (of minecraft and mod menu)?

**Comment by Boobies** [comment]
1.16.1, latest build for it on CurseForge, GUI scale does not seem to be relevant

https://imgur.com/sd0DJyj

**Comment by cs127** [comment]
It was a replaymod issue and it's fixed now.
https://github.com/ReplayMod/ReplayMod/issues/373
https://github.com/ReplayMod/ReplayMod/commit/5721b6f8c9b174f0c7cea1aa5c99b12c036b059d

**Comment by Prospector** [comment]
Ah, nice.
