### ISSUE TITLE
Modmenu-1.14.5+build.30 - Failed To Launch

### ISSUE THREAD

**Issue by Grecoton** [Prospector/ModMenu#143]
Description: when starting the launcher it throws an error and does not let the game start
![Anotación 2020-07-17 102359](https://user-images.githubusercontent.com/68435483/87803842-b46c7b00-c818-11ea-914b-bee9a7e9633d.png)
Fabric API = fabric-api-0.14.1+build.372-1.16
[latest.log](https://github.com/Prospector/ModMenu/files/4938613/latest.log)

**Comment by Prospector** [comment]
Update fabric loader
