### ISSUE TITLE
Optifabric Incompatibility

### ISSUE THREAD

**Issue by carson-mullaney** [Prospector/ModMenu#145]
I'm not really sure how to explain this one but optifabric, along with the most recent optifine pre-release (pre5), add 3 unknown mods to the bottom of the list.  They are slf4j-api, slf4j-simple, and zt-zip.  I'm not sure if this is a bug or just an incompatibility the user has to live with but I figured I would make it known.

**Comment by Prospector** [comment]
It's not an incompatibility, OptiFabric just provides those 3 libs. Unfortunately, Loom does not mark them with anything that I can uniquely identify, which means they show up even when libraries are hidden in the Mods screen.
