### ISSUE TITLE
addButton override breaks other menu button mods

### ISSUE THREAD

**Issue by Linguardium** [Prospector/ModMenu#149]
https://github.com/Prospector/ModMenu/blob/ce047f709b815b7195dca271a1bba3656f337628/src/main/java/io/github/prospector/modmenu/mixin/MixinTitleScreen.java#L38

This seems to be causing an issue with other mods adding buttons in certain locations. see https://github.com/KurodaAkira/RPG-Hud
They added a hardcoded offset due to this override changing how buttons are arranged on the menus (not really the best option)

https://github.com/KurodaAkira/RPG-Hud/issues/65#issuecomment-663856775

**Comment by Prospector** [comment]
Hmm, we sorta need an API for this don't we. Something to allow easy addition of buttons to screens.
