### ISSUE TITLE
[Enhancement] Mod Menu doesn't check if the icon for a mod is usable before using it

### ISSUE THREAD

**Issue by thakyZ** [Prospector/ModMenu#154]
When adding an icon for a mod that isn't a square (same width/height) Minecraft yells out errors.
I started talking to the author of the Bookworm library, and they don't use ModMenu as a dependency but the mod still yells when Bookworm's icon isn't square.
Here is the log:
https://pastebin.com/LgUXYKW7

Here is what the author said:
![image](https://user-images.githubusercontent.com/950594/91209679-ec40cb00-e6c0-11ea-95e4-44e13afcdb56.png)
He also wanted me to include that Bookworm doesn't use any JIJ or have any dependency on the mod menu mod
![image](https://user-images.githubusercontent.com/950594/91209737-067aa900-e6c1-11ea-80b3-31d6276dbf01.png)

**Comment by Prospector** [comment]
All icons should be square, as per the fabric.mod.json spec here: https://fabricmc.net/wiki/documentation:fabric_mod_json_spec

This is the same behavior as resource pack and data pack icons as well.
