### ISSUE TITLE
Crashes everytime I have mod menu locally

### ISSUE THREAD

**Issue by McGillicudy1** [Prospector/ModMenu#160]
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'modmenu'!
Exit Code: -1

I'm new to mods, but I have an up to date fabric api 1.16.2 and this is the error I get when ever I try and add mod menu. Its only client side as of now, does it need to be on the server too? What am I doing wrong.

**Comment by Prospector** [comment]
Could you provide a full log?

**Comment by Prospector** [comment]
Could not verify.
