### ISSUE TITLE
Enhancement: Ability to specify in fabric.mod.json for the mod to be hidden in mod menu.

### ISSUE THREAD

**Issue by ghost** [Prospector/ModMenu#163]
I'd like the ability for my mod to be hidden in mod menu as its just a wrapper mod for including its modules.  Just a simple custom hide field would be good.

**Comment by Prospector** [comment]
I could potentially add this, although in this case would it not be better to have the modules simply set the wrapper mod as their parent and then you can have them all collapse under it?

**Comment by ghost** [comment]
I want my modules to be able to be distributed separately while still having a parent, basically:

Download Module A:
Mod A
 - Module A

Download Module B:
Mod A
 - Module B

Download Wrapper:
Mod A
 - Module A
 - Module B
 - Module C
 - Module D

Wrapper would simply just be a bundle and wouldn't be included with the separate modules, and so I wouldn't want it to display in the mod menu.

**Comment by Prospector** [comment]
I see. Yeah, I'll get something for this added soon. 

I also want to maybe re-think how parents work, and allow non-mods to be parents, so that you don't have to have a dummy mod in order to have modules collapsed under one entry. I'm not sure the best way to go about doing that though, since the parent would still need metadata and an icon and stuff... hmm.

**Comment by Prospector** [comment]
It is worth noting though, that the parent mod doesn't have to be present. This is the case with Fabric API. When the full jar from CurseForge is installed, the `fabric` modid is present and all the modules are collapsed under it, while when it's not present, all the modules just show up individually in the list.

**Comment by Prospector** [comment]
So I've decided to not add this because I think it could be abused, however in the latest release you will be able to now have parents that aren't actually mods, if that helps.
