### ISSUE TITLE
Long descriptions do not render correctly

### ISSUE THREAD

**Issue by DeathsGun** [Prospector/ModMenu#172]
The DescriptionListWidget can't handle long descriptions like the Phosphor one.

![Screenshot 2020-11-16 at 21 37 51](https://user-images.githubusercontent.com/13536793/99305809-952c3b80-2854-11eb-9aec-cfdf4f77ede9.png)

**Comment by Prospector** [comment]
Huh, that is weird. It should have a scroll bar when it gets too long. I wonder why it doesn't anymore...

**Comment by DeathsGun** [comment]
Oh, then its more broken than I thought.

**Comment by DeathsGun** [comment]
It's looks like that because of `render` being overwritten the scrollbar doesn't render at all
