### ISSUE TITLE
Version 1.14.10+build.15 (the latest release on CF) has "unspecified" as the version

### ISSUE THREAD

**Issue by Minenash** [Prospector/ModMenu#174]
One of my mods has a "modmenu >= 1.12.0" requirement, and I started to get reports that it didn't work with the latest modmenu release. Specifically:
```
Could not find required mod: better_mod_button requires {modmenu @ [>=1.12.0]}
Creating Empty clause ?
```
After a bit of digging, I noticed that the version field in 1.14.10+build.15 was set to "unspecified" instead of "1.14.10+build.15"

**Comment by damunzy** [comment]
Modifying to the current version manually works: 
"version": "unspecified", **to** "version": "1.14.10+build.15",

I used 7-zip and didn't have to extract anything. Just opened in Notepad++, edited, saved, went back into 7-zip and clicked yes to update the file.

**Comment by Minenash** [comment]
Yup, in my reply to the reports my mod got, I had suggested the same, just thought I'd bring it up, since I doubt my mod was the only thing affected by it

**Comment by Prospector** [comment]
Whoops, ok. I've reverted this version since it seems super messed up.
