### ISSUE TITLE
Game crashes when going on mod options, now also crashes when clicking mod list.

### ISSUE THREAD

**Issue by mattioiscattio** [Prospector/ModMenu#181]
on 1.16.3 fabric, have tried the latest version for 1.16.4 and 1.16.1 (cant find one for 1.16.3) and the error still occurs, this was working fine before. 

[crash-2020-12-05_09.34.22-client.txt](https://github.com/TerraformersMC/ModMenu/files/5646798/crash-2020-12-05_09.34.22-client.txt)

crash report is above.

**Comment by Prospector** [comment]
This is the last version that supported 1.16.3 https://www.curseforge.com/minecraft/mc-mods/modmenu/files/3023985
