### ISSUE TITLE
Add config options to mod count

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [Prospector/ModMenu#183]
In fabric.mod.json, you can specify for a mod to parent another mod to make everything look nicer (seen below) with "modmenu:parent". The issue with this is that the sub-mod/child mod is not counted in the total number of mods, even though it should (in my opinion), because although it is an extension to the mod, it is still a mod in of itself, and many people (in my experience) use ModMenu to quickly check if the new mod they're using works, and if the number has not gone up, it may be a hassle to manually check if it is just a sub mod and has not been counted, or if there's a mod incompatibility issue or smth.

**Comment by DragonEggBedrockBreaking** [comment]
![image](https://user-images.githubusercontent.com/68545280/103086016-4738ef00-45db-11eb-8d9b-385490e9a5a0.png)

**Comment by DragonEggBedrockBreaking** [comment]
I use 38 mods, not including libraries. 8 of those are extensions and use the "modmenu:parent" function, so only 30 mods are counted.

![image](https://user-images.githubusercontent.com/68545280/103086126-a991ef80-45db-11eb-9f05-62274e213553.png)

**Comment by Prospector** [comment]
This is an intended feature, however maybe it should be an option.
