### ISSUE TITLE
I'm not getting any improvements

### ISSUE THREAD

**Issue by qfaq** [Prospector/ModMenu#187]
I came into this mod expecting high fps on my 2014 Macbook Pro to get it's last bit of life but to no surprise I have no performance gain. I'm still running at around 30-40 fps and I'm not sure why.

**Comment by NeusFear** [comment]
This is not a performance mod... This mod displays your mod list in a mod menu on the title screen. Try using a performance mod to improve performance. Not sure where you got the idea that this was one...
