### ISSUE TITLE
More flexible badges

### ISSUE THREAD

**Issue by williambl** [Prospector/ModMenu#191]
A proposal regarding the badge system:

 - replace the `BadgeType` enum with a `BadgeType` class which stores: `Text text`, `int outlineColor`, `int fillColor`, and `Predicate<ModMetadata> predicate`.
 - add a Badge registry, which holds a list of `BadgeType`s
 - add a `Collection<BadgeType> getModBadgeTypes()` to `ModMenuApi`, and hook it up to the badge registry
 - instead of the current hardcoded logic in `BadgeRenderer`, just do something equivalent to `BadgeRegistry.getBadgeTypes().stream().filter(badge -> badge.predicate.test(metadata)).forEach(badge -> drawBadge(matrices, badge, mouseX, mouseY))`
 
This would allow mods to add their own badge types, which could be useful for e.g. Patchwork-type projects without having to hardcode them all.

**Comment by Prospector** [comment]
Yeah...I'm mixed on it. On the one hand, I can see the use cases for this, but on the other, I don't want every mod to just give themselves a bright obnoxious badge that ruins the consistency of the UI. Hmm...

**Comment by williambl** [comment]
> I don't want every mod to just give themselves a bright obnoxious badge

Yeah, that is a potential issue. Not sure what could be done to mitigate that; though I hope most mods wouldn't do that.

**Comment by Prospector** [comment]
I think I would prefer to keep them hardcoded, however if anyone has a good reason for adding one (like the Patchwork one), just open an issue and I'll get it added.
