### ISSUE TITLE
mod_version was removed in commit 5f46eac8944bf07071ffb92525b7247386a8d06e, breaking mods which depend on modmenu

### ISSUE THREAD

**Issue by ImperatorStorm** [Prospector/ModMenu#193]
as said in title, commit 5f46eac8944bf07071ffb92525b7247386a8d06e removed `mod_version` from gradle.properties, leaving the mod with a `null` version and breaking any and all mods that depend on modmenu.

This has persisted into release v1.14.14

**Comment by Prospector** [comment]
Fixed in v1.14.15
