### ISSUE TITLE
Maven for 1.14.15

### ISSUE THREAD

**Issue by goatgitter** [Prospector/ModMenu#194]
Hi, I have a small mod which uses Mod Menu as a dependency.  I am not able to pull version 1.14.15 from Maven.  Did the URL change, or was there an issue posting to Maven?

**_gradle.properties_**

modmenu_version=1.14.15

**_build.gradle_**
dependencies {
...
modImplementation "io.github.prospector:modmenu:${project.modmenu_version}"

**_Build Error_**
> Could not resolve all dependencies for configuration ':modImplementation'.
   > Could not find io.github.prospector:modmenu:1.14.15.
     Searched in the following locations:
       - https://libraries.minecraft.net/io/github/prospector/modmenu/1.14.15/modmenu-1.14.15.pom
       - https://maven.fabricmc.net/io/github/prospector/modmenu/1.14.15/modmenu-1.14.15.pom
       - https://repo.maven.apache.org/maven2/io/github/prospector/modmenu/1.14.15/modmenu-1.14.15.pom
       - https://jcenter.bintray.com/io/github/prospector/modmenu/1.14.15/modmenu-1.14.15.pom
       -
Checking the usual URL (https://maven.fabricmc.net/io/github/prospector/modmenu/) does not show a folder for 1.14.15.

**Comment by Prospector** [comment]
Yes, the maven is now `https://maven.terraformersmc.com`
