### ISSUE TITLE
"Hidden mods" in config

### ISSUE THREAD

**Issue by Madis0** [Prospector/ModMenu#197]
I noticed that the new config has a node "hidden_mods", could you do an example on what should the contents look like?

**Comment by DragonEggBedrockBreaking** [comment]
there is a config gui in modmenu that allows you to toggle options

try playing around with options there

**Comment by Madis0** [comment]
Well, the only relevant option is Hidden Mods: Counted/Not Counted, but I do not see a button to hide specific mods, so I assume it is config-only.

**Comment by Prospector** [comment]
Yeah, it is config only. It's just an array of mod ids, so for example, this will hide Mod Menu:

```json
"hidden_mods" : [
    "modmenu"
]
```

If you need to figure out the ID of a mod, you can select it in Mod Menu and hover over the name on the right side of the screen. The ID should appear in a tooltip.
