### ISSUE TITLE
The "69" easter egg is broken

### ISSUE THREAD

**Issue by cs127** [Prospector/ModMenu#198]
Easter egg disabled:
![image](https://user-images.githubusercontent.com/56088587/106459961-dde4af80-64a7-11eb-965c-09dd14f99e46.png)

Easter egg enabled:
![image](https://user-images.githubusercontent.com/56088587/106460013-f05ee900-64a7-11eb-964a-4f93b7a997cc.png)

Minecraft version: 1.16.5
Fabric loader version: 0.11.1
Fabric API version: 0.30.0
Mod Menu version: 1.16.0

**Comment by Prospector** [comment]
Fixed in v1.16.1
