### ISSUE TITLE
Ammendment to the compact list mode

### ISSUE THREAD

**Issue by Minenash** [Prospector/ModMenu#203]
Since the reason for using the compact list mode is to be able to see more info, would it be possible for the "drag and drop" msg to be removed and the right side shifted up to see more of the description

**Comment by Prospector** [comment]
Not sure I really want to change the right side of the screen. I'd rather keep the current alignment and text as is regardless of list mode.

**Comment by Minenash** [comment]
The only reason I suggested it was because when the gui is set to auto/4, there's not much space for the description box, and getting rid of the msg, would increase the boxes height somewhere between 33% and 50% which is quite a bit. And I feel like this space issue is why people wanted a compact mode to begin with (to be able to see more mods because of how big the full size can be with high gui scales).

But yeah if you're against it, you can close this

**Comment by Prospector** [comment]
I think for now, I'm gonna say no to this.
