### ISSUE TITLE
License above credits?

### ISSUE THREAD

**Issue by Minenash** [Prospector/ModMenu#204]
I think the license should be above the credits, since a lot of people can be credited for a mod, but a mod can only have 1 license

**Comment by Prospector** [comment]
Actually, a mod can have as many licenses as it wants. Initially I put it at the end because it's sorta...boring information I guess? But it does sorta make sense for it to be higher.

**Comment by Minenash** [comment]
> Actually, a mod can have as many licenses as it wants

It can? I thought the license field was a string instead of an array.

**Comment by Prospector** [comment]
Nope, it can be either.
