### ISSUE TITLE
Game crash when opening minecraft

### ISSUE THREAD

**Issue by Oliver-makes-code** [Prospector/ModMenu#206]
I just downloaded the mod and when I ran it it gave me this error:

> Found conflicting mods: modmenu conflicts with {fabric @ [<0.30.0]}
>    Creating Empty clause ?

Please let me know if I'm just stupid and missing something obvious lmao

[crash-2021-01-25_12.50.07-client.txt](https://github.com/TerraformersMC/ModMenu/files/5907061/crash-2021-01-25_12.50.07-client.txt)

**Comment by Prospector** [comment]
You need to update Fabric API to something >= 0.30.0 https://www.curseforge.com/minecraft/mc-mods/fabric-api
