### ISSUE TITLE
plz fix icon

### ISSUE THREAD

**Issue by Desempregago** [Prospector/ModMenu#208]
![image](https://user-images.githubusercontent.com/14002834/106557686-18c70180-6501-11eb-8b63-ce324ae5ee2b.png)
Mod Menu v1.16.2 (for 1.16.5)

**Comment by Desempregago** [comment]
it also mentions some other mods, like `microconfig` and `dynamicentry`, which wasn't happening before updating

**Comment by Prospector** [comment]
Pushing a fix now
