### ISSUE TITLE
A Class is MISSING, it makes the game CRASH.

### ISSUE THREAD

**Issue by GitFox-0320** [Prospector/ModMenu#213]
I launch _Minecraft 1.16.5 Fabric_ with _ModMenu_, but the game **crashes**. This is _latest.log_:
`[16:05:36] [main/INFO]: Loading for game Minecraft 1.16.5`
`[16:05:40] [ForkJoinPool-1-worker-1/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:`
`- Unsupported root entry "$schema" at line 2 column 14`
`[16:05:42] [main/INFO]: [FabricLoader] Loading 96 mods: fabric-renderer-api-v1@0.4.1+ca58154a7d, fabric-keybindings-v0@0.2.1+ca58154a7d, roughlyenoughitems-api@5.9.1, notenoughcrashes@3.1.5, com_googlecode_json-simple_json-simple@1.1.1, snowy_leaves@1.16.1-1.3.1, held-item-info@1.1.3, inventoryprofiles@0.4.2, fabricloader@0.11.1, customskinloader@14.13-SNAPSHOT-214, fabric-structure-api-v1@1.1.4+ca58154a7d, fabric-containers-v0@0.1.10+ca58154a7d, colorunchained@1.1.1-1.16.4, fabric-object-builder-api-v1@1.9.3+ca58154a7d, com_cedarsoftware_json-io@4.10.1, fabric-dimensions-v1@2.0.2+ca58154a7d, java@8, fabric-game-rule-api-v1@1.0.6+ca58154a7d, fabric-api-base@0.2.0+daa38b3d7d, xaeroworldmap@1.11.11, ctm@0.2.1, fabric-rendering-data-attachment-v1@0.1.5+ca58154a7d, fiber@0.23.0-2, tooltiptooltips@1.0.1, fabric-textures-v0@1.0.6+ca58154a7d, roughlyenoughresources@2.1.3, fabric-rendering-fluids-v1@0.1.13+ca58154a7d, com_alibaba_fastjson@1.2.56, waila@1.9.22, fabric-blockrenderlayer-v1@1.1.5+ca58154a7d, fabric-lifecycle-events-v1@1.2.1+ca58154a7d, fabric-renderer-registries-v1@2.2.1+ca58154a7d, fabric-loot-tables-v1@1.0.2+ca58154a7d, fabric@0.30.0+1.16, fabric-particles-v1@0.2.4+ca58154a7d, fabric-networking-v0@0.3.2+ca58154a7d, betterpingdisplay@1.1, roughlyenoughitems-default-plugin@5.9.1, okzoomer@4.0.1+1.16.2, minecraft@1.16.5, fabric-networking-blockentity-v0@0.2.8+ca58154a7d, fabric-screen-handler-api-v1@1.1.1+ca58154a7d, horsestatsvanilla@4.1.4, modmenu@1.16.5, fabric-command-api-v1@1.0.10+ca58154a7d, jankson@3.0.1+j1.2.0, cloth-basic-math@0.5.1, fabric-screen-api-v1@1.0.0+c045166c7d, fabric-tool-attribute-api-v1@1.2.6+ca58154a7d, editsign@2.2.0, fabric-renderer-indigo@0.4.4+ca58154a7d, roughlyenoughitems-runtime@5.9.1, smoothboot@1.16.4-1.4.0, roughlysearchable@2.1.2+1.16.4, advancements-enlarger@0.2.3, cloth-client-events-v0@1.4.5, roughlyenoughitems@5.9.1, fabric-item-api-v1@1.2.1+ca58154a7d, fabric-crash-report-info-v1@0.1.3+ca58154a7d, fabric-events-interaction-v0@0.4.2+ca58154a7d, libgui@3.2.2+1.16.3, orderly@2.0.0-alpha.10-1.16, fabric-entity-events-v1@1.0.3+ca58154a7d, xaerominimap@21.2.0, fabric-rendering-v0@1.1.2+ca58154a7d, fabric-rendering-v1@1.5.1+ca58154a7d, overpowered_mending@2.2.2, fabric-key-binding-api-v1@1.0.2+ca58154a7d, better_mod_button@1.1.4, cloth-config2@4.8.3, smoothscrollingeverywhere@3.0.3-unstable, autoconfig1u@3.3.1, fabric-resource-loader-v0@0.4.2+ca58154a7d, inventoryhud@3.2.0, fabric-content-registries-v0@0.2.1+ca58154a7d, fabric-tag-extensions-v0@1.1.1+ca58154a7d, command-gui-buttons@1.1.0, fabric-biome-api-v1@3.1.1+ca58154a7d, appleskin@1.0.11, can-i-mine-this-block@1.0.2, architectury@1.5.105, fabric-registry-sync-v0@0.7.4+ca58154a7d, fabric-commands-v0@0.2.2+ca58154a7d, breakprogress@1.0.1, lightoverlay@5.6.1, betterf3@1.1.2, fabric-mining-levels-v0@0.1.3+ca58154a7d, fabric-networking-api-v1@1.0.1+ca58154a7d, fabric-events-lifecycle-v0@0.2.1+ca58154a7d, minimalmenu@1.16.5-0.0.5, ksrch@1.0.0, betterf1@1.16.4-1.0.0, fabric-models-v0@0.2.1+ca58154a7d, fabric-item-groups-v0@0.2.3+ca58154a7d, fabric-object-builders-v0@0.7.2+ca58154a7d, imblocker@1.0.11`
`[16:05:42] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2`
`Source=file:/D:/Minecraft/PCL2/.client/libraries/net/fabricmc/sponge-mixin/0.8.2+build.24/sponge-mixin-0.8.2+build.24.jar Service=Knot/Fabric Env=CLIENT`
`[16:05:54] [main/INFO]: Smooth Boot config initialized`
`[16:05:55] [main/WARN]: Could not download mappings, stack trace won't be deobfuscated`
`[16:06:05] [main/WARN]: Error loading class: io/github/prospector/modmenu/ModMenu (java.lang.ClassNotFoundException: io/github/prospector/modmenu/ModMenu)`

**Comment by Prospector** [comment]
Some mod is accessing Mod Menu internals. I can't tell you any more without a full log.

**Comment by coderbot16** [comment]
You need to remove Better Mod Button.

**Comment by Minenash** [comment]
Better Mod Button is also obsolete with the newest versions of mod menu

**Comment by GitFox-0320** [comment]
OK, I deleted _Better Mod Button_.
