### ISSUE TITLE
[Bug] Latest version Incompatible with Bedrockify Panorama

### ISSUE THREAD

**Issue by ZaneDragonBorn** [Prospector/ModMenu#215]
The newest version of the mod will give a weird visual bug with Bedorckify Panoramas. It was compatible with Older Versions
![image](https://user-images.githubusercontent.com/68198648/106978855-1cd66780-672b-11eb-9584-7780e900bada.png)

**Comment by Prospector** [comment]
I don't think there's much I can do about this. That mod is making changes to the UI and there's no real way for Mod Menu to be able to expect or account for them.
