### ISSUE TITLE
Crash on Startup from versions 1.15.0-1.16.5

### ISSUE THREAD

**Issue by Avakining** [Prospector/ModMenu#216]
All versions from v1.15.0 to v1.16.5 seem to crash on loading for me. Log for v1.16.5 and for the most recent unaffected version, v1.14.15, are below.

v1.16.5 Log: [https://paste.ee/p/eEaVm](https://paste.ee/p/eEaVm)
v.1.14.15 Log: [https://paste.ee/p/q7ESt](https://paste.ee/p/q7ESt)

**Comment by NeusFear** [comment]
Remove bettermodbutton
