### ISSUE TITLE
[Bug] Detecting Nonexistent mods

### ISSUE THREAD

**Issue by ZaneDragonBorn** [Prospector/ModMenu#218]
There is a bug on the Newest version where it will detect way more mods than the Amount installed.
![image](https://user-images.githubusercontent.com/68198648/107133782-d9f6ca00-68b9-11eb-9515-33351afc6133.png)
When inside the mod menu I only have 7 mods and 6 libraries but in Title I have 60 mods.

**Comment by Prospector** [comment]
Some mods contain other mods. If you want to hide mod children, you can do so in the Mod Menu options -> `Children: Not Counted`

**Comment by ZaneDragonBorn** [comment]
Ok Thanks! I always wanted to remove my childen! 👍
