### ISSUE TITLE
Crashes on boot up no matter what I do.

### ISSUE THREAD

**Issue by JMSBI** [Prospector/ModMenu#221]
I have the latest Fabric API 0.30.3 and removed all mods, yet it still crashes every time I load the game.
[crash-2021-02-20_10.58.51-client.txt](https://github.com/TerraformersMC/ModMenu/files/6015928/crash-2021-02-20_10.58.51-client.txt)

**Comment by Thysieboy** [comment]
I have the same exact issue. All different mods, though. Except for Sodium and the ModMenu, that is.
[crash-2021-02-20_22.19.15-client.txt](https://github.com/TerraformersMC/ModMenu/files/6016467/crash-2021-02-20_22.19.15-client.txt)

**Comment by coderbot16** [comment]
@JMSBI You need to install Cloth Config: https://www.curseforge.com/minecraft/mc-mods/cloth-config (https://github.com/OroArmor/Netherite-Plus-Mod/issues/69)

@Thysieboy No, that's not the exact same issue. SimpleZoom is abandoned, use [OK Zoomer](https://www.curseforge.com/minecraft/mc-mods/ok-zoomer) instead.

**Comment by Thysieboy** [comment]
Alright, for me the problem was the SimpleZoom mod, I have removed it now and it works fine. Appearently some sort of compatibility with the ModMenu is required for mods?
