### ISSUE TITLE
Handle mods that have broken ModMenu compatibility or break without Cloth Config better

### ISSUE THREAD

**Issue by coderbot16** [Prospector/ModMenu#222]
This code should be surrounded with a try-catch block, and any errors should be attributed to the mod instead and be non-fatal: https://github.com/TerraformersMC/ModMenu/blob/1.16/src/main/java/com/terraformersmc/modmenu/ModMenu.java#L51-L64

**Comment by Prospector** [comment]
Added in v1.16.8
