### ISSUE TITLE
Include so many mod from Fabric API

### ISSUE THREAD

**Issue by barraIhsan** [Prospector/ModMenu#227]
So, before all the mod from fabric API, is doesn't count (ex. `fabric-renderer-api-v1@0.4.1+ca58154a7d`, `fabric-keybindings-v0@0.2.1+ca58154a7d`) But now it count?
And also can you add an option to show the loaded mod?
![image](https://user-images.githubusercontent.com/57800056/109944710-137bf300-7d09-11eb-8768-6bbd36ed20f0.png)
Before it says `Mods (%s loaded)`
So I want an option to turn on that
![image](https://user-images.githubusercontent.com/57800056/109944762-21ca0f00-7d09-11eb-8037-5cbc2a5e0120.png)
Now its in the title screen
I also want an option to turn off this

**Comment by Prospector** [comment]
These options exist, you can change where the count is displayed and also whether or not to include libraries and children
