### ISSUE TITLE
Default getModId implementation crashes the game - ModMenu 1.10.5 for 1.15.2

### ISSUE THREAD

**Issue by The-Fireplace** [Prospector/ModMenu#230]
When the game loads, it will crash if getModId returns null, which is now the default implementation.
https://paste.ubuntu.com/p/mR5ybQz7h8/
The crash seems to come from [here](https://github.com/TerraformersMC/ModMenu/blob/1.15/src/main/java/io/github/prospector/modmenu/ModMenu.java#L72), because the ImmutableMap doesn't like null keys (And from the documentation I wouldn't expect it to be added as a null key either based on the documentation, which [says the modid will be pulled from the loader](https://github.com/TerraformersMC/ModMenu/blob/1.15/src/main/java/io/github/prospector/modmenu/api/ModMenuApi.java#L42).

**Comment by Prospector** [comment]
oh...this PR must have never been tested https://github.com/TerraformersMC/ModMenu/pull/192

**Comment by LainSar** [comment]
how do i fix it
