### ISSUE TITLE
Clickable link to licenses

### ISSUE THREAD

**Issue by Gamebuster19901** [Prospector/ModMenu#236]
It would be great if developers could add a clickable link to their license(s). Trying to do it now just results in grey text.

![image](https://user-images.githubusercontent.com/7155747/112706192-f4d8ca00-8e78-11eb-895e-45e00d7fcb46.png)

Perhaps the license field in the .json could additonally accept json objects with the parameters "name" and "url".

For example, the following json:
```json
{
  "license": [
  		{
  			"name": "Microsoft Game Content Usage Rules",
  			"url": "https://www.xbox.com/en-US/developers/rules"
		},
		"Example license 2",
		"Example license 3"
  	]
}
```
would look something like this:

![image](https://user-images.githubusercontent.com/7155747/112706565-73366b80-8e7b-11eb-8105-db8f99da19ca.png)

**Comment by actuallyasmartname** [comment]
This would look interesting.

**Comment by jackassmc** [comment]
This should be added to the [fabric.mod.json spec](https://fabricmc.net/wiki/documentation:fabric_mod_json_spec#optional_fields_metadata) first.
Please open an issue at https://github.com/FabricMC/fabric-loader/issues.

**Comment by Gamebuster19901** [comment]
> This should be added to the [fabric.mod.json spec](https://fabricmc.net/wiki/documentation:fabric_mod_json_spec#optional_fields_metadata) first.
> Please open an issue at https://github.com/FabricMC/fabric-loader/issues.

Wouldn't a custom field suffice?

**Comment by jackassmc** [comment]
Yes, it would be possible to add a custom field that accepts licenses as an object as you described. But then the license wouldn't be defined in the proper license field anymore, breaking fabric.mod.json spec compliance. There are workarounds, like a custom field that only contains the URL(s) for example, but that would be hacky.

It is possible to make a clickable link using the [Mod Menu metadata API](https://github.com/TerraformersMC/ModMenu/wiki/API#links). Does that work for you?

**Comment by jackassmc** [comment]
I'm closing this as resolved. Feel free to reopen if the spec gets updated.
