### ISSUE TITLE
[Enhancement] Ability to refresh and reload mods

### ISSUE THREAD

**Issue by NaiNonTH** [Prospector/ModMenu#239]
Be able to refresh and reload mods without re-entering Minecraft

**Comment by K0-RR** [comment]
This is just not possible. Mods need to be loaded by Mod Loader and Minecraft, how do you want ModMenu to handle this?

**Comment by Prospector** [comment]
Yeah, unfortunately this isn't possible due to how mods work.

**Comment by NaiNonTH** [comment]
> This is just not possible. Mods need to be loaded by Mod Loader and Minecraft, how do you want ModMenu to handle this?

> Yeah, unfortunately this isn't possible due to how mods work.

Understood. Have a nice day :)
