### ISSUE TITLE
[Suggestion] Hide config button if unused

### ISSUE THREAD

**Issue by InsomniaKitten** [Prospector/ModMenu#24]
If a mod does not register a config task then the button should not be displayed for its entry in the list.

**Comment by Prospector** [comment]
I did think about doing that but I figured it would be a bit more confusing if a button is missing than if it was just disabled with a tooltip. But I guess it's something to think about again.

**Comment by gbl** [comment]
I'd prefer the button to stay how it is; having it greyed out + tooltip makes it very clear to the user what's going on. Not having the button at all will just make users wonder what's broken instead of conveying a "nothing to configure here" message.

**Comment by InsomniaKitten** [comment]
A disabled config button for a mod that doesn't need a config implies that is intended to have one but has no yet implemented it
