### ISSUE TITLE
Support for FastChests

### ISSUE THREAD

**Issue by DeckerExpert** [Prospector/ModMenu#252]
[crash-2021-04-30_20.44.22-server.txt](https://github.com/TerraformersMC/ModMenu/files/6405723/crash-2021-04-30_20.44.22-server.txt)
I'm still unsure of what happened or the cause of this crash.

**Comment by coderbot16** [comment]
You're using an old version of ModMenu, try updating to the latest version available on 1.16.

**Comment by DeckerExpert** [comment]
I did try it, but it still didn't work. I did found the reason why it doesn't work, and it's not because I'm using an old version of ModMenu; ModMenu doesn't support FastChests.
FastChests is a mod that optimizes the chests to a huge margin, and ModMenu doesn't appear to support it.
I hope I get a word soon about this and hopefully even support for it.

**Comment by coderbot16** [comment]
Please send the new crash report that you're getting now, if it's different from before.

**Comment by jackassmc** [comment]
I can't reproduce this with `modmenu@v2.0.2+1.17` and `fastchest@1.2+1.17`.

Please reopen this issue if you still encounter this crash.
