### ISSUE TITLE
Save & Quit Bug

### ISSUE THREAD

**Issue by SmushyTaco** [Prospector/ModMenu#253]
If you edit the config of a mod and click save and quit and go back in the config right after without exiting the mod menu list GUI there are inconsistencies in the GUI. It seems to work properly if you edit a config, click Save & Quit, exit the mod menu mod list, and then go back to the config GUI but that extra step shouldn't be there. There's something off with the Save & Quit button.

**Comment by Prospector** [comment]
This would be a problem with the mod that adds the config GUI and would have nothing to do with Mod Menu.
