### ISSUE TITLE
Settings integration bug

### ISSUE THREAD

**Issue by thatDudo** [Prospector/ModMenu#254]
I am using cloth config:
Some other mods suffer the same issue like for example OK Zoomer.

### The Problem

When I am opening the settings from outside modmenu there are no problems at all.

Now I integrate the Settings Screen Builder into modmenu and open it. I can set all values just fine..
But when I leave those settings and find myself back inside the modmenu GUI, then reopen it:

The "Save" Button is already activated, and I cant change the value back, because the save button gets deactivated when switching the toggles back.

==> **Modmenu is reusing the same Screen object while its GUI is opened, while Cloth Config [explicitly stated not to do that](https://shedaniel.gitbook.io/cloth-config/using-cloth-config/creating-a-config-screen):**.

I've found [the code where that is happening](https://github.com/TerraformersMC/ModMenu/blob/9f4e048ecd293648d5f7ead626eee5eaae40c10e/src/main/java/com/terraformersmc/modmenu/gui/ModsScreen.java#L133).

### All you need to do:

[ModsScreen.java](https://github.com/TerraformersMC/ModMenu/blob/9f4e048ecd293648d5f7ead626eee5eaae40c10e/src/main/java/com/terraformersmc/modmenu/gui/ModsScreen.java)

### **Add**
```
// As I've looked trough the code I've found out that it relies on the screen being constantly initialized ;-; so sad
// This is to Re-Initialize a Screen once it was already used; true if Screen was used once
private ImmutableMap<String, Boolean> configScreenUsages = new HashMap<>();

public Screen buildConfigScreen(String modid) {
	try {
		return configScreen = ModMenu.getConfigScreen(modid, this);
	} catch (Throwable e) {
		LOGGER.error("Error from mod '" + modid + "'", e);
		return null;
	}
}
```
### **Modify**
**Line 116**
```
for (Mod mod : ModMenu.MODS.values()) {
	configScreenCache.put(modId, getConfigScreen(mod.getId()));
	configScreenUsages.put(mod.getId(), false);
}
```
### **Modify**
**Line 129**
```
ButtonWidget configureButton = new ModMenuTexturedButtonWidget(width - 24, paneY, 20, 20, 0, 0, CONFIGURE_BUTTON_LOCATION, 32, 64, button -> {
	final String modid = Objects.requireNonNull(selected).getMod().getId();
	// <-=<-=-===-FROM HERE-===-=->=->
	
	// If it was used already, create new screen
	if (configScreenUsages.get(modid)) {
		configScreenCache.put(modId, getConfigScreen(modid));
	}
	
	//  <-=<-=-===-TO HERE-===-=->=->
	final Screen screen = configScreenCache.get(modid);
	if (screen != null) {
		client.openScreen(screen);
	} else {
		button.active = false;
	}
},
```

### Images illustrating the problem
_Using Ok Zoomer_
1. Opening settings from mod menu button
![1](https://user-images.githubusercontent.com/58403773/117279640-338f7600-ae62-11eb-8d43-218b45ae2716.png)
2. Changing first two values
![2](https://user-images.githubusercontent.com/58403773/117279636-32f6df80-ae62-11eb-875b-8920598ed105.png)
3. Leaving
![3](https://user-images.githubusercontent.com/58403773/117279645-34280c80-ae62-11eb-9d48-f6ecc0d9e6e5.png)
4. Reopening -> Savebutton is already active; values cant be saved after changing them back to normal
![4](https://user-images.githubusercontent.com/58403773/117279643-338f7600-ae62-11eb-9b40-dc070f5e2beb.png)

**Comment by coderbot16** [comment]
Thanks for the detailed report! We'll look into getting this fixed.
