### ISSUE TITLE
[1.17] Mod Menu Breaks on 21w20a

### ISSUE THREAD

**Issue by Blobanium** [Prospector/ModMenu#259]
so apparently when i start up minecraft on 21w20a. i see that the mods button has gone missing.
![Capture](https://user-images.githubusercontent.com/45613796/118903614-019ffa00-b8cd-11eb-801b-63ff9de28982.PNG)

however this button is actually there and when i click it it seems to crash minecraft.

video to reproduce: https://streamable.com/x3hz7f

also i know 21w19a didn't do this issue. Only does it on 21w20a.

tell me if i need anything else thanks

**Comment by Blobanium** [comment]
oh god i almost forgot about the crash log.. here it is if you need it
[crash-2021-05-19_18.02.23-client.txt](https://github.com/TerraformersMC/ModMenu/files/6512275/crash-2021-05-19_18.02.23-client.txt)

**Comment by jackassmc** [comment]
This has been resolved and can be closed.
