### ISSUE TITLE
Mod total on title screen bug

### ISSUE THREAD

**Issue by ghost** [Prospector/ModMenu#260]
I was just opening fabric to play some more on my modded world, when I noticed that the total mods it said I had installed on the title screen was 53, and when I opened the actual menu, it said the correct amount which was 5. Can easily reproduce just by opening the client again. Will give more details if necessary.
![Screenshot (30)](https://user-images.githubusercontent.com/84940427/119901271-ed7a7f00-bf02-11eb-917f-20fe10f111b5.png)

**Comment by K0-RR** [comment]
Can you send a screenshot of the ModMenu in-game config screen?
You probably turned on "Libraries counting" and left "Libraries showing" off.

**Comment by ghost** [comment]
> Can you send a screenshot of the ModMenu in-game config screen?
> You probably turned on "Libraries counting" and left "Libraries showing" off.

It seems I am stupid. Yes, that did the trick. Thank you!
