### ISSUE TITLE
Opacity animation not handled correctly in 1.17

### ISSUE THREAD

**Issue by spnda** [Prospector/ModMenu#263]
![image](https://user-images.githubusercontent.com/43609023/121230178-34675d80-c88f-11eb-972d-b4564b2e5d96.png)

After the Mojang loading splash screen, nearly all buttons in the main menu have a short opacity animation, however the mod menu button does not.
This is with the current release of Minecraft 1.17 and fabric-api 0.34.9.

**Comment by jackassmc** [comment]
This was fixed in `v2.0.2`.
