### ISSUE TITLE
Suggestion: remember the scroll state of the mod list when you close/reopen it

### ISSUE THREAD

**Issue by gbl** [Prospector/ModMenu#27]
When a mod has several config options, you might want to open the config, then check the effects, repeatedly until you're content. It'd be nice if that didn't involve scrolling down every time you open the ModMenu Gui.

**Comment by BaronyCraft** [comment]
This is supposed to be implemented in 1.4.2, right? Because it isn't :(

**Comment by Prospector** [comment]
Oh...I actually seem to have misread the issue. I took thought it meant when you opened a config menu and went back or resized the window. I'm not sure I want it to save the scroll state when you entirely reopen the gui though, as usually you don't go back to the same thing you just looked at.

**Comment by Prospector** [comment]
Talked with a few other people on discord and came to the conclusion that I don't think this is a good idea for most cases
