### ISSUE TITLE
Mod Menu Overriding Alt Manager

### ISSUE THREAD

**Issue by ItsBearsie** [Prospector/ModMenu#271]
![Weird Menu](https://user-images.githubusercontent.com/84733392/121789927-1485b180-cb8f-11eb-8923-dbe39ba7873e.png)

**Comment by jackassmc** [comment]
Does this happen with version `2.0.2`?

**Comment by jackassmc** [comment]
Duplicate of https://github.com/TerraformersMC/ModMenu/issues/256. See https://github.com/TerraformersMC/ModMenu/issues/256#issuecomment-841809900 for a workaround.
