### ISSUE TITLE
Allow declaration and configuration of config button

### ISSUE THREAD

**Issue by ChloeDawn** [Prospector/ModMenu#272]
Currently, the config button presence relies on invoking the screen factory and checking for a non-null reference. I would like to have a button present without a screen and have control over that button to define a ClickEvent that opens my mod's respective config file. The non-null check could be moved to a dedicated method, and that method could be delegated to from a new API method that creates the button component.

**Comment by jackassmc** [comment]
By now users have learned that when they click a Mod Menu "Configure..." button they a presented with a screen inside the Minecraft client. Changing this to instead open a file outside of the Minecraft client breaks this expectation which is bad UX.

While no explicit support for custom behavior will be added it's still possible to do it if you really want to. You could make a screen that opens your config file and then closes itself, but I would recommend not doing that.
