### ISSUE TITLE
Where is the mod modImplementation url?

### ISSUE THREAD

**Issue by skylorbeck** [Prospector/ModMenu#274]
Seriousy, I am so lost.

**Comment by NeusFear** [comment]
https://maven.terraformersmc.com/ is where our mods reside now

**Comment by jackassmc** [comment]
And new versions of ModMenu will be at https://maven.terraformersmc.com/releases/com/terraformersmc/modmenu.

~https://maven.terraformersmc.com/releases/io/github/prospector/modmenu~ is deprecated.
