### ISSUE TITLE
Broken Icons

### ISSUE THREAD

**Issue by NotADinosaur** [Prospector/ModMenu#276]
It lists some mods I have as having broken icons. The mods have icons and I don't see anything wrong with them, what are the "requirements" for an icon to be not broken?

**Comment by jackassmc** [comment]
The requirement is following the [fabric.mod.json spec](https://fabricmc.net/wiki/documentation:fabric_mod_json_spec#optional_fields_metadata) (Optional fields (metadata) -> Icon).
If no icon is specified the fallback is to use `assets/{modid}/icon.png`.
If the fallback can't be found a generic icon (![unknown_icon.png](https://raw.githubusercontent.com/TerraformersMC/ModMenu/1.16/src/main/resources/assets/modmenu/unknown_icon.png)) is used and the warning is printed.

Please post your log or the names of the mods that are affected.

**Comment by NotADinosaur** [comment]
One of the mods is https://www.curseforge.com/minecraft/mc-mods/better-ping-display-fabric

**Comment by jackassmc** [comment]
> One of the mods is https://www.curseforge.com/minecraft/mc-mods/better-ping-display-fabric

That mod specifies its icon as `assets/modid/icon.png`, while the actual icon is located at `assets/betterpingdisplay/icon.png`. So when loading the icon an error occurs and the default generic question mark icon is used. This is a problem with that mod.

This could have been easily seen in the log, please post a log in your next bug report.
