### ISSUE TITLE
Version 2.0.1 for MC 1.16.5 not on Modrinth (or CurseForge)

### ISSUE THREAD

**Issue by FintasticMan** [Prospector/ModMenu#277]
I'm not sure if this is the right place to put this, but version [2.0.1](https://github.com/TerraformersMC/ModMenu/releases/tag/v2.0.1) isn't available on Modrinth or CurseForge.  
Is there a reason for that, or was that just left out by accident?

**Comment by Prospector** [comment]
I believe it was a messed up release.
