### ISSUE TITLE
maven repo down?

### ISSUE THREAD

**Issue by KrisCris** [Prospector/ModMenu#278]
<img width="982" alt="Screen Shot 2021-07-02 at 3 58 04 PM" src="https://user-images.githubusercontent.com/38860226/124241394-4ebeef00-db4e-11eb-8f7a-1cea3f7eba09.png">

**Comment by NeusFear** [comment]
Yes, waiting on the members with access to come online. This isn't really a modmenu issue so I will close it, but [here](https://discord.gg/jEGF5fb) is the link to our discord, I'll make sure to post an update there once it's back up and running.
