### ISSUE TITLE
Cloudflare host maven.terraformersmc.com is down => cannot use in mod development

### ISSUE THREAD

**Issue by vlad2305m** [Prospector/ModMenu#280]
Today, 6th July, in the evening maven.terraformersmc.com stopped responding causing gradle to output `Could not GET 'https://maven.terraformersmc.com/releases/com/terraformermc/modmenu/2.0.2/modmenu-2.0.2.pom'. Received status code 521 from server: Origin Down`

**Comment by KosmX** [comment]
They should put some information about it outside of their Discord server.

You can use modrinth API: https://api.modrinth.com/maven/maven/modrinth/modmenu/maven-metadata.xml

Or TerraformersMC Github archive: https://github.com/TerraformersMC/Archive
To use as a maven repo, raw access to the archive:
`https://raw.githubusercontent.com/TerraformersMC/Archive/main/`

**Comment by KosmX** [comment]
https://twitter.com/TerraformersMC/status/1412699712419893257

**Comment by ghost** [comment]
@TerraformersMC/modmenu This can be closed now

**Comment by Prospector** [comment]
This should be resolved now https://twitter.com/TerraformersMC/status/1417309020986036226
