### ISSUE TITLE
Crash when press Mod List Button

### ISSUE THREAD

**Issue by M4DMAXX** [Prospector/ModMenu#282]
I play on 1.16.2 and got the crash wen i press Mods in the Main Menu.

actually i have the Mod Version 1.16.9 for Minecraft 1.16.5

before i try to use the Version 1.14.6+build 31 for Minecraft 1.16.2
but with this Version Minecraft never start and crash instant

Below the Crash Logs 
[Crash Mod Menu 1.16.2.txt](https://github.com/TerraformersMC/ModMenu/files/6790268/Crash.Mod.Menu.1.16.2.txt)
[Crash Mod Menu 1.16.5.txt](https://github.com/TerraformersMC/ModMenu/files/6790267/Crash.Mod.Menu.1.16.5.txt)

Hope anyone can help me there.. thx much :)

**Comment by jackassmc** [comment]
The 1.16.2 crash is caused by one of your mods using the new Mod Menu API, which wasn't available in Mod Menu 1.14.6+build 31. Sadly that means that if you want to stay on Minecraft 1.16.2 you can't use the incompatible mod.

The 1.16.5 crash is not as obvious, please try without any other mods and see if it still crashes. If it does crash please also post the log.

**Comment by M4DMAXX** [comment]
I try with just the Mod Menu and it still crash after press Mods Button

[Crash only Mod Menu 1.16.5.txt](https://github.com/TerraformersMC/ModMenu/files/6790479/Crash.only.Mod.Menu.1.16.5.txt)

Im new at Fabric. Is on the 1.16.2 a Hint which Mod are use the newer API?

thx for your help

**Comment by jackassmc** [comment]
> I try with just the Mod Menu and it still crash after press Mods Button

This isn't Minecraft 1.16.5, it's still 1.16.2. Please update to Minecraft 1.16.5 and try again.

> Im new at Fabric. Is on the 1.16.2 a Hint which Mod are use the newer API?

No, but you can try it with half the mods removed and keep going until you've found it.

**Comment by M4DMAXX** [comment]
> This isn't Minecraft 1.16.5, it's still 1.16.2. Please update to Minecraft 1.16.5 and try again.

 Ah yes my mistake... for 1.16.5 i need to wait then... actually slow connection speed...


I think i found the Mod... I started with all mods but without Mod Menu and got message that First Person Mod require Mod Menu... After remove First Person Mod and start without Mod Menu the Game start normal... but with Mod Menu für 1.16.2 it still crash...

below the actuall Log with removed First Person Mod and 1.16.2 Mod Menu

[Crash Mod Menu with removed Mod.txt](https://github.com/TerraformersMC/ModMenu/files/6790612/Crash.Mod.Menu.with.removed.Mod.txt)

**Comment by M4DMAXX** [comment]
Edit: Miss click on Close... my sorry

**Comment by jackassmc** [comment]
> I think i found the Mod... I started with all mods but without Mod Menu and got message that First Person Mod require Mod Menu... After remove First Person Mod and start without Mod Menu the Game start normal... but with Mod Menu für 1.16.2 it still crash...

It's still the same error, caused by a mod that uses the new Mod Menu API.
Leave Mod Menu enabled and disable other mods until pressing the Mods button in the main menu doesn't crash anymore.

**Comment by M4DMAXX** [comment]
> It's still the same error, caused by a mod that uses the new Mod Menu API.
> Leave Mod Menu enabled and disable other mods until pressing the Mods button in the main menu doesn't crash anymore.

Thx... i try it now... just wonder that i got now Error that Mod Menu is missing without it... nevermind.. thx

**Comment by M4DMAXX** [comment]
I finally found the secound mod it was "Smoothboot 1.16.5" I now look for 1.16.2 Version and if not exist leave it...

Thank you for your help

**Comment by M4DMAXX** [comment]
I use now Smoothboot 1.16.4 - 1.4.0

Now works all and Mod Menu dont crash! Thx. Closed

**Comment by M4DMAXX** [comment]
I use now Smoothboot 1.16.4 - 1.4.0

Now works all and Mod Menu dont crash! Thx. Closed
