### ISSUE TITLE
The display position of the ModMenu button is wrong

### ISSUE THREAD

**Issue by Peter-JY** [Prospector/ModMenu#284]
Just after I installed this Mod, the button of this Mod and another button comes from another mod was coincident, and the this button comes from ModMenu covered the other button.
And, if I set to show this instead of Minecraft Realms, it can display correctly. If I set to show this below Minecraft Realms or beside Minecraft Realms, this issue will show.

Besides, only in 1.16.5 can see this issue. I'll put a photo of 1.14.4 that where should the buttons display.

----------------------------------------------------------
Game version: 1.16.5
Game Language: Both English and Chinese (some photos I took and upload here is in Chinese, but I'm sure you can match them with correct English)
ModMenu version: 1.16.9

----------------------------------------------------------
Below:
![Minecraft 1 16 5 2021_7_13 16_49_22](https://user-images.githubusercontent.com/63086083/125422536-735482a1-e606-463c-b3d2-6b1caa49b479.png)
Beside:
![Minecraft 1 16 5 2021_7_13 16_50_00](https://user-images.githubusercontent.com/63086083/125422515-b609442b-2927-4e09-81e0-5e92fa29e3af.png)
Icon:
![Minecraft 1 16 5 2021_7_13 16_51_23](https://user-images.githubusercontent.com/63086083/125422496-9cc0cb61-f0e5-4bf4-8f45-6dd2b6124172.png)
Correct place of below (in 1.14.4):
![Minecraft 1 14 4 2021_7_13 16_52_04](https://user-images.githubusercontent.com/63086083/125422478-15d954ca-2956-4bf4-b5d4-8a958f4fc73c.png)

The button that was covered by ModMenu's button is from Replay Mod.

**Comment by jackassmc** [comment]
I can't reproduce this with Mod Menu 1.16.9 and Replay Mod 2.5.2. Please update to the latest versions and reopen this issue if you still experience this problem.

**Comment by Peter-JY** [comment]
ModMenu 1.16.9 is the latest version for Minecraft 1.16.5......

**Comment by Peter-JY** [comment]
Newer versions are for 1.15.2 and 1.17, but the versions for 1.15.2 and 1.17 can't be loaded by Minecraft 1.16.5.

**Comment by Peter-JY** [comment]
And, Replay Mod's latest version is 2.5.2.

**Comment by Peter-JY** [comment]
So could you solve this problem?

**Comment by jackassmc** [comment]
> Game version: 1.16.5
> Game Language: Both English and Chinese (some photos I took and upload here is in Chinese, but I'm sure you can match them with correct English)
> ModMenu version: 1.16.9

You reported your Minecraft version as 1.16.5 and Mod Menu version as: 1.16.9. You did not specify the version of Repay Mod.

I cannot reproduce the issue with Minecraft version 1.16.5 (same as yours), Mod Menu version 1.16.9 (same as yours), and Replay Mod version 2.5.2 (might be different from yours).
