### ISSUE TITLE
1.17.1 Compatibility

### ISSUE THREAD

**Issue by jakey1995abc** [Prospector/ModMenu#288]
Quite a few mod developers include ModMenu as a dependency in CurseForge for Minecraft 1.17.1 but as ModMenu does not have any files marked as compatible with 1.17.1, including any of these mods in a modpack will make an old version of ModMenu install which is not compatible with Minecraft 1.17.1, breaking modpacks until the original mod which apparently depends on ModMenu is removed. 

Please Could you mark the 1.17 versions of ModMenu (at least the one's which are compatible) as being compatible with Minecraft 1.17.1 so that it fixes all these mods, and also allows users to include your mod in their modpacks :)

**Comment by jackassmc** [comment]
There are currently technical difficulties preventing a new release but the fix is already merged and 1.17.1 compatibility will be added soon(tm). See https://github.com/TerraformersMC/ModMenu/pull/289 for more details.

**Comment by jackassmc** [comment]
I have been given Curse Forge and Modrinth permissions and have added 1.17.1 as supported version.

Thanks for the report @jakey1995abc and the quick PR @Vaerian!
