### ISSUE TITLE
Add Liberapay Language Keys

### ISSUE THREAD

**Issue by gudenau** [Prospector/ModMenu#296]
Would be nice if you added language keys for [Liberapay](https://liberapay.com/), it is very similar to Patreon just different.

**Comment by jackassmc** [comment]
Sure, feel free to open a PR adding it to [en_us.json](https://github.com/TerraformersMC/ModMenu/blob/1.17/src/main/resources/assets/modmenu/lang/en_us.json) in the 1.16 and 1.17 branches.

**Comment by K0-RR** [comment]
I don't quite understand what this issue us about but other services like liberapay worth mentioning are:
https://www.buymeacoffee.com/
https://ko-fi.com/
https://flattr.com/
https://opencollective.com/
https://coindrop.to/
