### ISSUE TITLE
Mod Menu is Incompatible with Fabric 1.16.4

### ISSUE THREAD

**Issue by HOI4Player** [Prospector/ModMenu#299]
Whenever I try to launch the game, the game crashes and says Mod Menu is incompatible with Fabric.

**Comment by jackassmc** [comment]
Please download a version of Mod Menu that is compatible with your Minecraft version. Mod Menu 1.14.13 should work for you.

**Comment by haykam821** [comment]
You need the latest version of Fabric API for 1.16, which is currently [0.37.1](https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/3398544). [Mod Menu 1.16.11](https://www.curseforge.com/minecraft/mc-mods/modmenu/files/3400184) will work as long as you have an updated Fabric API.
