### ISSUE TITLE
Realms GUI not shifted correctly (button is, rest isn't)

### ISSUE THREAD

**Issue by gbl** [Prospector/ModMenu#30]
Without ModMenu:

http://imgur.com/uSN1csel.png

With ModMenu:

http://imgur.com/UHb3Tzfl.png

The button itself gets nudged up a bit, but the blue blinking thing and the icon don't.

**Comment by Prospector** [comment]
Info for me on solving: https://discordapp.com/channels/507304429255393322/507982478276034570/577332496295919632

**Comment by Prospector** [comment]
Oops, this was solved in v1.5.4; forgot to close
