### ISSUE TITLE
Mod is only using deprecated 'modmenu:clientsideOnly' custom value but it is not.

### ISSUE THREAD

**Issue by K0-RR** [Prospector/ModMenu#300]
I was getting this: `WARNING! Mod ambientenvironment is only using deprecated 'modmenu:clientsideOnly' custom value! This is no longer needed and will be removed in 1.18 snapshots.`

so I deleted the
```
  "custom": {
    "modmenu:clientsideOnly": true
  },
```

from the fabric.mod.json file but for some reason, the warning still shows up.

https://github.com/TerraformersMC/ModMenu/wiki/API
If I don't add any Discord link or library badge then I should not have a `modmenu` JSON object within the `custom` object, right?

**Comment by jackassmc** [comment]
> [...] the warning still shows up.

This is not possible as far as I'm aware. Please upload the mod jar that is causing this issue.

> https://github.com/TerraformersMC/ModMenu/wiki/API
> If I don't add any Discord link or library badge then I should not have a `modmenu` JSON object within the `custom` object, right?

Correct, it is completely optional.

**Comment by K0-RR** [comment]
Ok, this was caused because after you edit the fabric.mod.json file and save it you need to "update the archive" - 
![Screenshot from 2021-07-31 17-56-48](https://user-images.githubusercontent.com/43277609/127745508-51b8e3ef-f52c-4316-a741-d0a9323a711e.png)

The popup got under the main window and I didn't see it.

Sorry!
