### ISSUE TITLE
Easter egg badges

### ISSUE THREAD

**Issue by Kore-Development** [Prospector/ModMenu#303]
The Easter Egg badges are not rendering properly.
[Click to show screenshot](https://kurwa.club/u/4IumY)

**Comment by K0-RR** [comment]
Nice website. Do you by any chance have an invite code?

**Comment by Kore-Development** [comment]
> 
> 
> Nice website. Do you by any chance have an invite code?

Ask in their Discord https://kurwa.club/discord
I don't want to post an invite on a public repo
