### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by jacesthing** [Prospector/ModMenu#304]
I have multiple mods loaded on fabric, and i think it would be very useful to use the ModMenu mod, but whenever i use the mod the game crashes. I know its that mod because when i dont use it, it works perfectly fine, but when i launch Minecraft with Modmenu, it crashes. I can provide more details if asked, all help is appreciated.

**Comment by jackassmc** [comment]
Please post a complete crash log.

**Comment by jacesthing** [comment]
How do i see crash logs?

**Comment by jackassmc** [comment]
[Tutorials/How to get a crash report - Official Minecraft Wiki](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)

**Comment by jackassmc** [comment]
I'm closing this for lack of a log, feel free to reopen with one.
