### ISSUE TITLE
Crash with Architectury

### ISSUE THREAD

**Issue by maicol07** [Prospector/ModMenu#305]
Crash when I type a character in the mod menu search bar.

Crash report: [bytebin.lucko.me/9lzLNmrMLI](https://bytebin.lucko.me/9lzLNmrMLI)

**Comment by jackassmc** [comment]
Could you please try removing mods until it doesn't crash anymore? The goal is to have the least amount of mods that together cause this problem.

**Comment by jackassmc** [comment]
This appears to be a duplicate of https://github.com/TerraformersMC/ModMenu/issues/249.
