### ISSUE TITLE
Minecraft Error stating mod menu did it

### ISSUE THREAD

**Issue by Lionhitch** [Prospector/ModMenu#307]
Every time I open up minecraft with the 1.16.4 version of the mod (the latest version of it) fabric errors and the crash log says it is the issue.
![MMCrash](https://user-images.githubusercontent.com/88068220/129298566-aafd361c-6572-4d1c-b242-f2cdef334a2e.PNG)

**Comment by jackassmc** [comment]
Should work with Mod Menu 1.16.11, see https://github.com/TerraformersMC/ModMenu/issues/299#issuecomment-890370438.
