### ISSUE TITLE
Conflicts with Fabric API

### ISSUE THREAD

**Issue by SolidBlock-cn** [Prospector/ModMenu#309]
Cannot load game with both API and ModMenu installed because:
```
[11:31:07] [main/WARN]: Warnings were found! 
 - Conflicting versions found for fabric-api-base: used 0.3.0+a02b44633d, also found 0.3.0+a02b446318
 - Conflicting versions found for fabric-screen-api-v1: used 1.0.4+155f865c18, also found 1.0.4+198a96213d
```
Fabric API version 0.37.2
Mod Menu version: 2.0.4
Game version: 1.17.1

**Comment by jackassmc** [comment]
That's only a warning, it does not stop the game from loading.

I just tested with

> Fabric API version 0.37.2
> Mod Menu version: 2.0.4
> Game version: 1.17.1

and everything worked.
