### ISSUE TITLE
Selected mod buttons are overly-cached

### ISSUE THREAD

**Issue by Boundarybreaker** [Prospector/ModMenu#32]
Mod Menu 1.5.0-78, API 0.2.7+126, Loader 0.4.2+132
![2019-04-28_22 36 46](https://user-images.githubusercontent.com/6722691/56877911-21260a80-6a06-11e9-8972-03a21959f281.png)

Config button doesn't exist, even for mods that register config overrides

**Comment by Prospector** [comment]
Should be resolved in v1.5.1; Let me know if it isn't!
