### ISSUE TITLE
"website" & "issues" buttons do not update

### ISSUE THREAD

**Issue by robosoup2** [Prospector/ModMenu#33]
when i select mods, the icon & description update, but **Website** and **Issues** will link to the first mod in the list alphabetically. when i cancel and go back to mod list, the buttons have updated, but if the selected mod doesn't have these links set up then they can't be clicked, and so they can't be updated again.
hope that was clear, i tried to take screenshots but the program i use doesn't work for minecraft i guess

**Comment by Prospector** [comment]
oh shoot yeah, I broke this when cleaning up the code

**Comment by Prospector** [comment]
Same issue as in #32

**Comment by Prospector** [comment]
Should be resolved in v1.5.1; Let me know if it isn't!

**Comment by robosoup2** [comment]
wow! thanks so much! works great!
