### ISSUE TITLE
Scrolling down the mod list shows invisible items

### ISSUE THREAD

**Issue by Knito58** [Prospector/ModMenu#34]
The list seems to be empty after 2nd page but the items are still clickable. Have about 50 mods installed now. After searching with pattern scrolling not works anymore.

**Comment by Hellzbellz123** [comment]
it seems to only show about 20 mods for me, how about you Knito?

**Comment by Knito58** [comment]
@Hellzbellz123  Same for me. Thanks for seconding me. I really thought that only happens to me.

**Comment by Hellzbellz123** [comment]
yeah it seems to be a bug, if you happen to remember mod names you can filter the list to show ones past the 20 limiut

**Comment by Knito58** [comment]
Exactly.
