### ISSUE TITLE
Mod just...isnt working?

### ISSUE THREAD

**Issue by notmudzy** [Prospector/ModMenu#36]
have both the fabric launcher and API installed. i downloaded the file directly into my mods folder like i usually do (if this could be the cause let me know? but i dont think it is? could be wrong, i have before).

The menu just...wont show up. lol. ive tried restarting the game multiple times and the menu is nowhere to be found. I'm assuming this means that it just somehow isn't working correctly? It just ... is refusing to play nice with the launcher or something for me. if anyone knows what's wrong and would walk me through lmk.

**Comment by Prospector** [comment]
What do you mean? There's no button?

**Comment by snostormjp** [comment]
Adding a comment as I was having this issue, and resolved it.  If your mods folder is linked fabric does not seem to load the mods.  for example I am on linux and soft-linked ~/.minecraft/mods to ~/.minecraft/mods-fabric-1.14.4 the modmenu  mod never loaded, removing the link and just copying the folder fixed the issue
