### ISSUE TITLE
mod menu is causing my game to crash

### ISSUE THREAD

**Issue by TheFizzy** [Prospector/ModMenu#360]
[crash-2021-10-30_17.35.57-client.txt](https://github.com/TerraformersMC/ModMenu/files/7446217/crash-2021-10-30_17.35.57-client.txt)

**Comment by TheFizzy** [comment]
[latest.log](https://github.com/TerraformersMC/ModMenu/files/7446218/latest.log)

**Comment by jackassmc** [comment]
This appears to be an issue with an invalid Mod Menu config file.

Please try deleting your `modmenu.json` config file and if the game still crashes upload it here like you uploaded the logs.

**Comment by TheFizzy** [comment]
> This appears to be an issue with an invalid Mod Menu config file.
> 
> Please try deleting your `modmenu.json` config file and if the game still crashes upload it here like you uploaded the logs.

where can i find it?

**Comment by TheFizzy** [comment]
> This appears to be an issue with an invalid Mod Menu config file.
> 
> Please try deleting your `modmenu.json` config file and if the game still crashes upload it here like you uploaded the logs.

Is it the mixins.modmenu.json file?

**Comment by jackassmc** [comment]
> where can i find it?

It's in the same folder where all other mod config files are in. If you have the `mods` folder open (the folder with all the mod .jar files) you can go up one level (to the folder that has the `mods` folder in it) and in that folder there should be a `config` folder. The `modmenu.json` file should be in this `config` folder.

**Comment by TheFizzy** [comment]
> > where can i find it?
> 
> It's in the same folder where all other mod config files are in. If you have the `mods` folder open (the folder with all the mod .jar files) you can go up one level (to the folder that has the `mods` folder in it) and in that folder there should be a `config` folder. The `modmenu.json` file should be in this `config` folder.

Theres only class files in the config folder

**Comment by TheFizzy** [comment]
> > where can i find it?
> 
> It's in the same folder where all other mod config files are in. If you have the `mods` folder open (the folder with all the mod .jar files) you can go up one level (to the folder that has the `mods` folder in it) and in that folder there should be a `config` folder. The `modmenu.json` file should be in this `config` folder.

It works now thank you so much
