### ISSUE TITLE
If the Fabric API fatjar isn't present, the Fabric API collapsible will not be properly made

### ISSUE THREAD

**Issue by altrisi** [Prospector/ModMenu#364]
First thing to note is that it won't be considered a library and will therefore be shown even with libraries hidden, but also the icon, name and description will be missing.

With fatjar:
![imagen](https://user-images.githubusercontent.com/17107132/140647516-dd25b191-125c-4b12-9318-8fa828042894.png)

With only some modules, that come bundled by ModMenu itself or may have been manually installed by the user:
![imagen](https://user-images.githubusercontent.com/17107132/140647587-74abc579-7058-4ccb-bae6-4b98105cbb0e.png)

**Comment by jackassmc** [comment]
Thank you for this bug report! This will be fixed in a future version of ModMenu.

**Comment by Prospector** [comment]
I've improved this slightly in v3.1.0 for 1.18.2, but it could use more work.
