### ISSUE TITLE
my mods are not showing up

### ISSUE THREAD

**Issue by Santiproispapi** [Prospector/ModMenu#365]
every time i get do install a new mod it don't show

**Comment by chris0462** [comment]
same did u find a fix

**Comment by jackassmc** [comment]
ModMenu gets the list of mods from Fabric and by default displays all mods that are not marked as a library.

If you are adding a library and want to see it in ModMenu you can enable the display of libraries in ModMenu's settings.

If you are adding a mod that isn't a library and it isn't showing up in ModMenu it means that Fabric hasn't loaded the mod. Please consult the [Fabric Wiki on how to add mods](https://fabricmc.net/wiki/tutorial:adding_mods).
