### ISSUE TITLE
where MC1.16.1, v1.12.2? im trying to install tas

### ISSUE THREAD

**Issue by PlayerPro342** [Prospector/ModMenu#369]
how i can find it and stuff help pls

**Comment by jackassmc** [comment]
Old versions of ModMenu can be found on [GitHub releases](https://github.com/TerraformersMC/ModMenu/releases), on [Modrinth](https://modrinth.com/mod/modmenu) and on [CurseForge](https://www.curseforge.com/minecraft/mc-mods/modmenu).
