### ISSUE TITLE
Manningham Mills (Farbic-ASM) showing up in Mod Menu

### ISSUE THREAD

**Issue by Eiion** [Prospector/ModMenu#371]
With Minecraft v1.18 Manningham Mills (which apparently is Farbic-ASM if I'm informed correctly) shows up in the Mod Menu causing confusion what this mod (i.e. Manningham Mills) is supposed to be when nothing like it was downloaded and put into the mods folder by the user.

With it apparently being part of Fabric-ASM which is part of Optifabric (from what I've gathered) should this not be a hidden mod?

(https://github.com/FabricMC/fabric/issues/1876#issue-1069287439)

**Comment by Turtle418** [comment]
I have this issue too

**Comment by jackassmc** [comment]
This is caused by the deprecation of the old syntax of marking mods as libraries (`"modmenu:api" : true`).

To mark a mod as a library in ModMenu 3+ the new syntax is:
```
"custom": {
    "modmenu": {
        "badges": [ "library" ]
    }
}
```
