### ISSUE TITLE
Question: ModMenu build dependency

### ISSUE THREAD

**Issue by quiqueck** [Prospector/ModMenu#377]
I am a Contributer to BCLib (a utility library for BetterEnd and BetterNether) and we support ModMenu as it is an insanely helpful utility for players. However, we want to get rid of the dependency in our build environment. I did some testing and adding `ConfigScreenFactory` as well as `ModMenuApi` would allow us to have ModMenu integration without needing the build-dependency. Is it ok, if we include those files in our Repository. Currently I added the following comment to every file, but I am happy to change the wording: 

> // This File was included from TerraformersMC/ModMenu
// to enable a ModMenu-Integration without having to
// compile against the actual plugin in an attempt
// to reduce dependencies

Players will of course have to install ModMenu for this integration to work. It is just about our build system. Please let us know if you'd prefer that we not include those interfaces

**Comment by jackassmc** [comment]
Yeah that's fine.

Generally speaking if you ever want to do something like this you can go by the license. ModMenu is licensed under the MIT license, which is a permissive license. Meaning you can do almost anything you want with ModMenu's code. Check out https://tldrlegal.com/license/mit-license or the infobox at the top of the [LICENSE](https://github.com/TerraformersMC/ModMenu/blob/1.18/LICENSE) file. TLDRLegal states that one must include the copyright notice and license notice in all copies or substantial uses of the MIT licensed work.
I'd argue that what is happening here is not a substantial use of the work. But if you want to make absolutely sure you follow the license you can paste the contents of the [LICENSE](https://github.com/TerraformersMC/ModMenu/blob/1.18/LICENSE) file at the top of the files you have copied from ModMenu. That way you include the copyright notice and the license notice.

**Comment by quiqueck** [comment]
Thanks for getting back to us. I added the License to the head of the files. And while the License would allow us to include the code, we wanted to ask anyway to make sure you don't mind. :)
