### ISSUE TITLE
plz add support for 1.12.2

### ISSUE THREAD

**Issue by Deviken** [Prospector/ModMenu#384]
this mod was so good and it makes my game better than ever.But sadly it doesnt support 1.12.2,it will be great if its gonna support 1.12.2 in the future

**Comment by Felix14-v2** [comment]
I think it should be suggested in the [Legacy Mod Menu repo](https://github.com/BoogieMonster1O1/ModMenu).

**Comment by Prospector** [comment]
We only support recent versions, sorry
