### ISSUE TITLE
CONFLICT

### ISSUE THREAD

**Issue by saphsara** [Prospector/ModMenu#388]
hi, I am using your mod with blockus mod and when i go to craft blocks from the blockus mod they turn into minecraft transit railway stone bricks instead of the colored bricks i want to create.. it is the same crafting pattern in the crafting box your mod is overridding the other mod. can this be fixed? or do i have to chose which mod to keep? thank you.

**Comment by haykam821** [comment]
Mod Menu is a client mod and therefore shouldn't affect recipe outputs. Your registry sync is likely causing this issue; can you share a full mod list?

**Comment by saphsara** [comment]
Adorn (by Juicebus)
    Artisanat (by Hugman_76)
    Extended Block Shapes 扩展方块形状 (by SolidBlock_)
    Bottle Your Xp (Fabric) (by Serilum)
    Trinkets (Fabric) (by EmilyPloszaj)
    Collective (Fabric) (by Serilum)
    Comforts (Fabric) (by TheIllusiveC4)
    AppleSkin (by squeek502)
    Architectury API (Fabric) (by shedaniel)
    Xaero's World Map (by xaero96)
    Custom fences and walls (by theradiantraptor)
    Simple Backpack [FABRIC] (by kwpugh)
    Croparia v3 [FORGE/FABRIC] (by Dalarion01)
    Culinaire (by Hugman_76)
    Applied Energistics 2 Wireless Terminals (by Mari_023)
    Blockus (by Brandcraft_)
    Mod Menu (by ProspectorDev)
    Full Slabs (by micalobia)
    Simple Graves (by Speechrezz)
    Universal Ores (Fabric) (by Hugman_76)
    Roughly Enough Items Fabric/Forge (REI) (by shedaniel)
    Copper Armor & Tools [Fabric] (by agorasim20)
    Dawn API (by Hugman_76)
    Colored Lights (Fabric) (by gegy1000)
    Mo' Structures (Fabric) (by ffrannny)
    Croptopia's Chocolaterie (by slomax907)
    Patchouli (Fabric) (by williewillus)
    Fabric Language Kotlin (by modmuss50)
    Iron Chests for Fabric (by cyberanner)
    Promenade (by Hugman_76)
    Clumps (by Jaredlll08)
    Croptopia [FABRIC/FORGE] (by thethonk)
    Cloth Config API (Fabric) (by shedaniel)
    Minecraft Transit Railway (by jonafanho)
    Cloth API (Fabric) (by shedaniel)
    Block Of... [FABRIC] (by space_goat3)
    Botania (Fabric) (by williewillus)
    FPS Reducer (by bre2el)
    Stonecutter Recipe Tags (by tropheusj)
    Fabric API (by modmuss50)
    Mo Glass (by alexander9892)
    Advanced Netherite [FABRIC] (by AutovwLive)
    Applied Energistics 2 (by AlgorithmX2)
    Mouse Tweaks (by YaLTeR)
    Consistency+ (by Cart3r1234)
    Xaero's Minimap (by xaero96)
    Inventory Sorting (by Kyrptonaught)

**Comment by saphsara** [comment]
any idea how i can fix this .. if it is a registry sync issue?

**Comment by saphsara** [comment]
i think i posted this in the wrong mod issue page i am sorry
