### ISSUE TITLE
Feature Request: add tooltips to the Website and Issues buttons

### ISSUE THREAD

**Issue by calloatti** [Prospector/ModMenu#39]
Feature Request: add tooltips to the Website and Issues buttons so the user can see the actual url without having to click the button.

**Comment by Prospector** [comment]
Why? That seems incredibly unuseful

**Comment by calloatti** [comment]
Really? The feature that displays the target URL of a link when you hover over it, in the bottom left, in any modern browser seems like a very useful feature.

**Comment by Prospector** [comment]
But just click on it
