### ISSUE TITLE
3.0.1 not working for 1.18.2

### ISSUE THREAD

**Issue by henkelmax** [Prospector/ModMenu#391]
Version 3.0.1 does not work for 1.18.2, despite being marked as compatible with 1.18.2.
I'm assuming this is caused by the outdated version of Fabric API that's shipped within the mod.

https://gist.github.com/henkelmax/2011e36a8eed6cf4130f6d4878f13b6f

**Comment by Prospector** [comment]
Ah. If you install the correct Fabric API version, the error should be fixed, however I will unmark the version as supported and release a fix tomorrow.

**Comment by Prospector** [comment]
Releasing a fix now
