### ISSUE TITLE
Add support to open the mod's config without Mod Menu's dependency

### ISSUE THREAD

**Issue by JuggleStruggle** [Prospector/ModMenu#398]
As the title says, it would be nice if I didn't have to bundle Mod Menu as a dependency just to show the configuration menu while not really using other features.

The main reason why I mention this is because I typically don't like adding libraries to my mods if they aren't really used by the mod itself as that only creates unwanted dependencies.

My thought so far is to use the same way as one would do when wanting to add a config screen but instead of using `ModMenuApi` as the implementing interface, one can use `Function<Screen, Screen>` (or `UnaryOperator<Screen>`) where the first `Screen` type represents the previous screen and the second `Screen` represents the "config" screen. Instead of using `getModConfigScreenFactory()`, `apply(Screen)` is used instead.

**Comment by haykam821** [comment]
Are you wanting to get rid of Mod Menu as a compile-time dependency? Mod Menu does not need to be a runtime dependency or bundled because the entrypoint will only be called when Mod Menu is installed.

**Comment by JuggleStruggle** [comment]
> Are you wanting to get rid of Mod Menu as a compile-time dependency? Mod Menu does not need to be a runtime dependency or bundled because the entrypoint will only be called when Mod Menu is installed.

Apologies for not being around that it took 2 years for me to reply (lost interest and came back recently). Anyways, that's not the point. What I'm saying is that I don't want to add an optional dependency to my mod just to use one of its classes in order to gain access to the config menu when the solution above will suffice enough. If I wanted to use the extra features it comes with, I'd gladly include it on the build file and make use of it.

The reason why I can use Fabric API as a dependency is because there's more to it that the mod needs, such as registering stuff (like keybinds) or getting around things that Vanilla likely doesn't support but the API does. Mod Menu for me is adding extra information for just the case the user has the mod and to have them access the configuration without needing to be in-game.
