### ISSUE TITLE
Weblate for 1.17 branch has merge conflicts

### ISSUE THREAD

**Issue by K0-RR** [Prospector/ModMenu#399]
It may be caused by https://github.com/TerraformersMC/ModMenu/pull/358#issuecomment-1055750186 but it seems like the issue also affects Catalan (et_ee) language.
https://hosted.weblate.org/projects/fabric-modmenu/1-17/#alerts

![Screenshot from 2022-03-15 18-29-16](https://user-images.githubusercontent.com/43277609/158438601-7a6ef602-320e-430e-9003-c8d74435241c.png)
![Screenshot from 2022-03-15 18-33-29](https://user-images.githubusercontent.com/43277609/158438616-7caeca3c-7474-496a-b72d-649bdeb20210.png)

**Comment by jackassmc** [comment]
Fixed, thanks for reporting!
