### ISSUE TITLE
Homepage link does not wrap and is not clickable

### ISSUE THREAD

**Issue by UpcraftLP** [Prospector/ModMenu#4]
![image](https://user-images.githubusercontent.com/10714589/53685094-89ae7f00-3d16-11e9-9019-ecc0280ec557.png)

The homepage link does not wrap, nor is it clickable.

**Comment by Prospector** [comment]
technically fixed in the latest version because links no longer display :P

Once Fabric Loader updates their API to include links in the new stuff I'll implement it properly

**Comment by Prospector** [comment]
when I re-add this it'll be a button instead of a link so it doesn't need wrapping :P
