### ISSUE TITLE
Suggestion: add a button to see the actual fabric.mod.json content

### ISSUE THREAD

**Issue by calloatti** [Prospector/ModMenu#40]
A button to see the actual fabric.mod.json content in the right pane

**Comment by Prospector** [comment]
Why do you think this would be useful?

**Comment by calloatti** [comment]
To easily check the values in the file, without having to unzip the jar. Making it easier to see and report problems.

This is an example: https://github.com/modmuss50/OptiFabric/issues/16

**Comment by Prospector** [comment]
I think this is a bit out of scope. Mod Menu's not a debug tool
