### ISSUE TITLE
22w12a breaks Mod Menu

### ISSUE THREAD

**Issue by AzureDoom** [Prospector/ModMenu#405]
Using this in my snapshot modding using the 1.19 version you have here: https://www.curseforge.com/minecraft/mc-mods/modmenu/files/3570652

Worked in 22w11a but due to the Options changes in 22w12a, this is broken. https://gist.github.com/AzureDoom/c4b638018919f535d4245220cf478665

**Comment by Prospector** [comment]
I just released a 1.19 version that supports 22w15a
