### ISSUE TITLE
Oh well i saw this

### ISSUE THREAD

**Issue by Petrichorean** [Prospector/ModMenu#406]
![image](https://user-images.githubusercontent.com/93509907/161166461-cbaa8d0b-e227-486e-bbaa-02370d922b04.png)

idk why

**Comment by Petrichorean** [comment]
I had to edit because the other screenshot was completely black but I'm keeping the mod cause a lot of people downloaded it

**Comment by MediocreShrimp** [comment]
I saw the same thing on mine. After a quick google i found a few other threads like this all created on April 1st talking about the same issue. I think it's just an April fools joke lol

**Comment by thepigeongenerator** [comment]
I was just updatin' mah mods. I was aware of april fools so I wanted to avoid the internet for a while and just play on my server. BUT IT SLIPPED RIGHT PAST ME XD. dammit.

**Comment by ghost** [comment]
I saw this while playing the game and immediately came to the github page to see if its reported and well I guess it is.

**Comment by ghost** [comment]
i have this to, the mod menu is saying that the mod menu is a virus it is saying watch out i am a virus but i think its a bug

**Comment by Petrichorean** [comment]
> I have this too, the mod menu is saying that the mod menu is a virus it is saying watch out I am a virus but I think its a bug

Well maybe but it's April, so April fools day (I might have changed your text because idk)

**Comment by ghost** [comment]
> > I have this too, the mod menu is saying that the mod menu is a virus it is saying watch out I am a virus but I think its a bug
> 
> Well maybe but it's April, so April fools day (I might have changed your text because idk)

It was a joke and is normal now
