### ISSUE TITLE
Maven link 1.15

### ISSUE THREAD

**Issue by Johannes7k75** [Prospector/ModMenu#407]
Maven link 1.15 doesnt work

**Comment by Prospector** [comment]
What link are you using? Please be more specific when reporting issues

**Comment by Johannes7k75** [comment]
The Mave link from the [1.15 branch](https://github.com/TerraformersMC/ModMenu/tree/1.15)

here the link [Maven Link](https://maven.fabricmc.net/io/github/prospector/modmenu/)

returns `404 Not Found`

**Comment by Prospector** [comment]
Ah. The new maven link is https://maven.terraformersmc.com/releases and the latest Mod Menu version for 1.15 can actually be found under `com.terraformersmc.modmenu` instead of the old `io.github.prospector.modmenu` https://maven.terraformersmc.com/releases/com/terraformersmc/modmenu/1.10.6
