### ISSUE TITLE
Crash on launch 22w14

### ISSUE THREAD

**Issue by energy11a** [Prospector/ModMenu#409]
Crashes on launch
https://www.curseforge.com/minecraft/mc-mods/modmenu/files/3570652
0.13.3 fabric
[crash-2022-04-07_20.35.00-client.txt](https://github.com/TerraformersMC/ModMenu/files/8445315/crash-2022-04-07_20.35.00-client.txt)
Crashes on launch even with no other mods except dependencies.

**Comment by Prospector** [comment]
I just released a version that supports the latest 1.19 snapshot, 22w15a
