### ISSUE TITLE
Suggestion: rearrange the controls to use wasted space and align search box width

### ISSUE THREAD

**Issue by calloatti** [Prospector/ModMenu#41]
Instead of this:

![image](https://user-images.githubusercontent.com/12817862/58291746-e610c000-7d94-11e9-89ac-94593bea6272.png)

Maybe something like this:

![image](https://user-images.githubusercontent.com/12817862/58291722-d2655980-7d94-11e9-9ed6-fd5b3b73adbf.png)

**Comment by Prospector** [comment]
Hmm..not sure about this. It kinda throws off the nicely spaced alignment of everything

**Comment by Prospector** [comment]
Gonna reject this, though I do think I'll figure out something to do with that space eventually.
