### ISSUE TITLE
Mod Menu Options Configuration Reset

### ISSUE THREAD

**Issue by vrgtics** [Prospector/ModMenu#410]
hi, I always got annoyed by the _following pictures_ of Your mods "Options Configuration"

[https://imgur.com/a/CVObTit](url)
![2022-04-08_09 24 38](https://user-images.githubusercontent.com/99676066/162345667-3a81bc91-7bcf-4fcb-8b4f-d4b3ac989dd7.png)

sometime I don't remember and accidently click those button what I Don't know it.
I want to reset those buttons, but it was what file I can delete to make it **reset To Default**..

Regards.

**Comment by Prospector** [comment]
You can delete the file in `<game directory>/config/modmenu.json` and the file will be freshly regenerated
