### ISSUE TITLE
Mod Menu Removing "Copyright Mojang AB. Do not distribute"

### ISSUE THREAD

**Issue by SHXRKIEgg** [Prospector/ModMenu#411]
Hi, the "Copyright Mojang AB. Do not distribute" has changed to a button in the main menu so it is being removed with your mod added. You should fix this asap. This also happened with another mod but for FORGE and seeing the same on FABRIC

**Comment by Prospector** [comment]
Do you know which Minecraft version changed it to a button?

**Comment by SHXRKIEgg** [comment]
Oh yeah sorry forgot to say its 1.18.2, also i think it was a button the person told me or it got moved not sure.

**Comment by Prospector** [comment]
Releasing a fixed version 3.1.1 now.

**Comment by SHXRKIEgg** [comment]
Cool Cool thanks
