### ISSUE TITLE
Mods

### ISSUE THREAD

**Issue by Vaky333** [Prospector/ModMenu#422]
Hi, I have all the mods installed and minecraft opens perfectly but when I enter my world there's no mods and on the modmenu says that I don't have any installed. Someone knows about this problem?

![image](https://user-images.githubusercontent.com/101039157/167293281-234e246b-4f8a-4a39-a2fa-a661dc467ec3.png)
![image](https://user-images.githubusercontent.com/101039157/167293292-aab1c514-cc23-473d-9b16-d2a00cbec21a.png)

**Comment by jackassmc** [comment]
Just Enough Items and Corail Tombstone are both Forge mods and are not loaded by Farbic. The other mods are loaded, Essential is already shown but libraries are hidden by default, you can show them by clicking on the "Libraries: Hidden" button.
