### ISSUE TITLE
Some new added languages do not work

### ISSUE THREAD

**Issue by NaiNonTH** [Prospector/ModMenu#428]
The file names of newly added languages aren't corrected from the source. Please consider changing those files names into something appropriate.

**Comment by NaiNonTH** [comment]
Example: #429 -- Renamed th.json to th_th.json

**Comment by jackassmc** [comment]
Mod Menu now uses Crowdin for translations, language files should be named correctly going forward.

**Comment by NaiNonTH** [comment]
Nice
