### ISSUE TITLE
Crash when resizing window with text in mod search field

### ISSUE THREAD

**Issue by Blayyke** [Prospector/ModMenu#43]
Game crashes when the window is resized with any text in the mod search field. Just being selected or being empty does not cause the crash, however it is really slow for the window to be resized anyway.

My log: https://gist.github.com/Blayyke/1ec9c5b5a682f57d7e0d22359f2f3b2c
Log from calloatti: https://paste.ee/p/m9Rlk

Also worth pointing out is that the glassential stacktrace is printed every single time the text field is clicked. Does not cause any crashes though.

**Comment by Prospector** [comment]
Figured this out, I did an oopsie
