### ISSUE TITLE
Feature Request: Tag Search Filtering

### ISSUE THREAD

**Issue by EntranceJew** [Prospector/ModMenu#44]
I sometimes quickly need to find something, but the size of the menu with 200+ mods loaded can leave me having to memorize certain mod names and what they do, it would be handy if there were buttons that I could toggle that filtered the results by:

- mods that have a config button
- mods that are tagged as APIs
- mods that are tagged as Client-Only

This would make it a lot easier to manage the configuration and balance phase of creating a mod loadout.

**Comment by Prospector** [comment]
The latter two are already a thing, actually. You can search for, "api" or "clientside" and it will filter accordingly. The config one is a good idea though.
