### ISSUE TITLE
Hide child mods (modules) from the mod count

### ISSUE THREAD

**Issue by robosoup2** [Prospector/ModMenu#46]
i have 2 mods installed, fabric api and this one. but it says i have 26 mods loaded, i don't know where they're coming from but it wasn't like this in older versions. If this is intentional behavior then i would say, I can see how it would be helpful to mod makers but for an average user it's more confusing/misleading/overwhelming. maybe this could be on a toggle? thanks again for making this mod
https://i.imgur.com/6ByPtio.png

**Comment by Prospector** [comment]
Fabric API has loads of modules now, so they're all displayed. I think I will make it a toggle, however, but maybe not for a while.

**Comment by Prospector** [comment]
Implemented in v1.6.2...not configurable yet unfortunately, it will always hide children from the count.
