### ISSUE TITLE
Quilt Loader Error

### ISSUE THREAD

**Issue by mucookul** [Prospector/ModMenu#462]
I got a error, here is picture:
![Capture](https://user-images.githubusercontent.com/71291707/176004106-141473f0-aa6e-4dfb-94ad-c0b6b82cdc5e.PNG)

**Comment by Prospector** [comment]
The version of Mod Menu you're using requires at least Minecraft 1.19.1

**Comment by mucookul** [comment]
1.19.1 isn't out tho

**Comment by mucookul** [comment]
do i just wait until it releases?

**Comment by mucookul** [comment]
nvm
