### ISSUE TITLE
1.19 Modmenu + Emotecraft Crash

### ISSUE THREAD

**Issue by ImJunglee** [Prospector/ModMenu#463]
When having Fabric API 0.57.0, Fabric 0.14.8, Modmenu 4.0.0 and Emotecraft 2.1.3-SNAPSHOT. Minecraft's crashing.
See crash report. 
Thank you
[crash-2022-06-30_00.59.10-client.txt](https://github.com/TerraformersMC/ModMenu/files/9016507/crash-2022-06-30_00.59.10-client.txt)
!

**Comment by jackassmc** [comment]
This appears to be an Emotecraft related issue, please report it at [KosmX/emotes](https://github.com/KosmX/emotes).
