### ISSUE TITLE
Double click to open mod options

### ISSUE THREAD

**Issue by Liberato116** [Prospector/ModMenu#464]
Since there's no interaction with the mod list when double-clicking, I figured using it to open the mod settings would help reduce the hassle of tweaking settings and trying them out in-game over and over again.

**Comment by jackassmc** [comment]
The [ModSettings](https://github.com/magicus/ModSettings) mod provides an easy to access configuration screen for all installed mods.

**Comment by Prospector** [comment]
Added in 6.1.0-rc.3
