### ISSUE TITLE
Keybind option missing on 1.19

### ISSUE THREAD

**Issue by ardissaps** [Prospector/ModMenu#468]
![image](https://user-images.githubusercontent.com/82106625/177458492-a4ca8eaf-88e0-428f-9390-8a966fb63ba1.png)
![image](https://user-images.githubusercontent.com/82106625/177458504-a198eb10-e1e2-4e50-a0e0-58501f6f351f.png)

**Comment by MagnusHJensen** [comment]
There has not been a release for 1.19 after the 7th of June.
The keybind addition was merged on the 11th of June.

**Comment by jackassmc** [comment]
It is now available in [v4.0.3 for 1.19](https://modrinth.com/mod/modmenu/version/4.0.3).

**Comment by ardissaps** [comment]
Thank you!
