### ISSUE TITLE
Is it necessary to load all config screens on opening the Mod Menu?

### ISSUE THREAD

**Issue by SolidBlock-cn** [Prospector/ModMenu#477]
I found that when clicking the "Mod Menu" button, config screen for all mods that have config screens are created (`ModsScreen#init`). I don't think it necessary. It may waste times when entering mod menu screen.

**Comment by jackassmc** [comment]
It is necessary for the search bar filter for configurable mods. In English a search containing one of `configurations` `configs` `configures` `configurable` `options` only shows mods that have a config screen.
Some languages have translations for this, see the `modmenu.searchTerms.configurable` key in the [language files](https://github.com/TerraformersMC/ModMenu/tree/1.19/src/main/resources/assets/modmenu/lang).
