### ISSUE TITLE
Mod Icon Transparency

### ISSUE THREAD

**Issue by Milouvert** [Prospector/ModMenu#48]
I don't know if there were big changes between those two versions, but in version 1.5.4, mod icons could use transparent backgrounds, I just updated to 1.6.1 and it doesn't seem to be transparent anymore.
![ModMenuTransparency](https://user-images.githubusercontent.com/38847520/58772377-aca33600-8586-11e9-954a-b7e39860cb9d.png)

Using Fabric API v0.3.0 b175

**Comment by Prospector** [comment]
This is intentional, to give mods more uniformity.
