### ISSUE TITLE
Feature Request: Ability to bind keys to config toggles 

### ISSUE THREAD

**Issue by TheFantasticLoki** [Prospector/ModMenu#483]
Hi was looking around trying to find another mod that might have done this or some way to accomplish this but can't figure anything out so figured I would throw it here. I would like to see a way to add some of the config toggles to the controls keybinds menu. I have a few mods that don't have keybinds for some features and you have to go through the config menu in your mod in order to toggle the feature and it's quite annoying at times so I'd love a way to bind them to keys and preferably just the ability to add an entry to the key binds menu like a normal mod would in order to keep compatibility with other mods like minemenu refabricated etc.

**Comment by haykam821** [comment]
Due to the way that Mod Menu's configuration API is designed, there isn't a simple way to provide key bindings for anything short of simply opening a mod's configuration screen.
