### ISSUE TITLE
Fully Customizable Button

### ISSUE THREAD

**Issue by Echo69420** [Prospector/ModMenu#489]
I would kinda consider this an issue, because I would kinda say it's the reason I don't use mod menu. It would be cool if you could totally customize the mods button, so that it could replace "Give Feedback" AND "Report Bugs" (in game) in the menu but then also choose something else for the startup menu without changing the in game menu (when you press esc) when you have "adjacent" selected it replaces "Report Bugs" with the mods button so I think there should also be an option to replace "Give Feedback" and "Report Bugs" to make one big button. And also have an option remove it on either menu (startup menu or in game menu) too, as well as another option to replace the "Quit Game" button. Sorry if this was too long I never really find the right words to say lol. But thanks and have a good day. 

(Also I think a /mods command with a toggle for it would be cool just to list the mods in the chat)

**Comment by vrad-exe** [comment]
Seems like the main thing you're suggesting here is decoupling the mods button's pause menu position from its title screen position (which is what I came here to suggest). For the pause menu postions, I'd suggest:

- Replace Bugs/Feedback (behavior you suggested)
- Below Bugs/Feedback (current behavior for Below Realms or Replace Realms)
- Replace Bugs only (current behavior for Adjacent)
- Icon
- Disabled (don't show mods button in-game, only on main menu like in Forge)

The reason I'm suggesting this myself is that I set the mods button to replace realms in my modpack, which causes it to move below bugs/feedback in the pause menu, but I'd like it to remain like in adjacent mode where it replaces report bugs. Tying the pause menu position to the title screen position doesn't make much sense considering that the rest of the options presented in these two menus are completely different from each other.

**Comment by Prospector** [comment]
This has been mostly implemented in 1.19.4, it has a separate option but there's no Replace Bugs and Feedback option at the moment.

**Comment by Echo69420** [comment]
YOOO NO WAY IDK WHO YOU ARE OR IF U MANAGE THIS AT ALL BUT TY LET'S GO

**Comment by Echo69420** [comment]
YOOO NO WAY IDK WHO YOU ARE OR IF U MANAGE THIS AT ALL BUT TY LET'S GO

**Comment by Echo69420** [comment]
U still can't rid of it on either page tho
