### ISSUE TITLE
Suggestion: Some minor layout changes

### ISSUE THREAD

**Issue by Sollace** [Prospector/ModMenu#49]
![image](https://user-images.githubusercontent.com/6429283/59359612-f3372400-8d2e-11e9-85f0-b914f775d362.png)

1. I centered the search box and window title to be consistent with other minecraft screens.
2. Added a placeholder text to the search box
3. Details window for mods now has a scrollbar so they can contain any amount of content the modder wants and still fit into the same space.
4. Moved the link buttons into a category below the description (also in the scrolling panel)

Some of these changes were in response to the space issue mentioned at https://github.com/Prospector/ModMenu/issues/23

Extra links/credits could also be included below the buttons with horizontal rules between them to differentiate the sections.

**Comment by Prospector** [comment]
1, perhaps, I did consider that.
2, no for consistency with the world selection search box
3 already exists
4, idk, doesn't look as good imo

**Comment by Sollace** [comment]
```3 already exists```
It doesn't really look like it has a scrollbar, though?

```4, idk, doesn't look as good imo```
Fair enough. 

3+4 are in part addressing the space limitations you mentioned in the other issue. The centering was the main initial idea I had.

And placeholder text is just- It looks nice, okay? :L

**Comment by Prospector** [comment]
There's no scroll bar unless there's enough text to warrant one

**Comment by Prospector** [comment]
Gonna reject this, as I'm not a huge fan of how the button placement looks. Perhaps something like this would be considered but atm I believe it's fine enough until I can come up with a better solution.
