### ISSUE TITLE
Mod configuration button without clicking on mod

### ISSUE THREAD

**Issue by sisby-folk** [Prospector/ModMenu#492]
Similar to #464 

I can get easily frustrated figuring out which mods have configuration options and which ones don't - having the button to configure a mod visible and clickable on the mod list would help a lot.

![image](https://user-images.githubusercontent.com/55819817/197955805-2258dc4d-1f02-4199-9977-874a8fc59434.png)

**Comment by Prospector** [comment]
You can filter by configurable mods easily by typing in "config" in the search box

**Comment by sisby-folk** [comment]
This is useful! is there some way to reasonably make this the default?

**Comment by sisby-folk** [comment]
To add some clarification here, (and because the other half of this conversation is more #493) I'm looking to aid players in situations where they might not be able to find the config button, or not know it's the right one. Because it appears on a different part of the screen than where the mod is listed, it's easy to miss for someone less experienced.

It's personally the button we use the most in modmenu, and I can only assume it's one of the main ones people press besides clicking on mods, so I figured I'd toss the suggestion out,

**Comment by Xetaxheb** [comment]
While this is definitely an option I think the existing configure button should at least be bigger/more prominent instead of just the little slider bars. Maybe reuse the slider bars for the list-config but change the existing button to say "Configure" and be as wide as Issues/Website? As-is it's honestly somewhat inconvenient when configuring a bunch of mods because of having to click that tiny box on the other side of the screen... and potentially non-instructive to people who don't know it's there.

**Comment by Prospector** [comment]
Added in 6.1.0-rc.3, the mod icon is now clickable to open the config screen and you can now double-click a mod widget to open it as well.

**Comment by sisby-folk** [comment]
oh that's swag as hell we just finished setting up the default hotkeyed
config mode stuff for our pack too

**Comment by sisby-folk** [comment]
Oh that's swag a s hellwe just finished setting up the default hotkeyed config mode stuff for our pack too. 

I'm assuming we'll keep an eye on this for a portential 1.20 pack update (it's not backport stuff right?)

![image](https://user-images.githubusercontent.com/55819817/225783806-139c590b-9732-4410-bdd4-192bfa2572a1.png)

**Comment by Prospector** [comment]
It may be backported, we'll see. I don't have the energy for that right now lol. Your screenshot just reminded me compact mode exists... I should check that it works in compact mode.

**Comment by Prospector** [comment]
ah.
![image](https://user-images.githubusercontent.com/6166773/225784469-f00ab224-6cb1-4c06-92fd-0cb682359fc3.png)

**Comment by sisby-folk** [comment]
Minor note: compact mode without badges is also slightly smaller at least
in our testing.

**Comment by Prospector** [comment]
hmm, I don't think that should be the case?

**Comment by sisby-folk** [comment]
Just reviewed - seems you're right there, we may just add badges back to our pack config then
