### ISSUE TITLE
The version for 22w44a is released as a release version rather than an alpha

### ISSUE THREAD

**Issue by haykam821** [Prospector/ModMenu#497]
I'm concerned about the release of version 5.0.0, since it means that a release version is being used for snapshots and the new APIs will not be available on the current release version of Minecraft.

Could a versioning system similar to Terraform's be used in addition to a backport of #495? In particular:

- Commit 3c79724251461576f138c566eb3d4de05d3ea200 would be released as Mod Menu 4.1.0 for Minecraft 1.19.2 on the `1.19` branch
- Commit 302a4070bf489b0acc9fc7f4c88ef34bc74816d5 would be released as Mod Menu 5.0.0-alpha.1 for Minecraft snapshot 22w44a on the `1.19.3` branch

**Comment by jackassmc** [comment]
The major version was incremented because of the new badge API, so any release containing the the new API needs to be v5 dot something.

I'm also confused about the new versioning, are these snapshots part of 1.19 or 1.20? Or both?

Luckily the 1.19 branch release failed so v5.0.0 doesn't exist yet.

**Comment by haykam821** [comment]
I don't think the badge API is a breaking change since its only addition to the API surface is a default interface method, which shouldn't conflict with existing API implementations.

The new system for Minecraft snapshots means that 22w44a does not technically have a target version, but blog posts indicate that these snapshots will be for minor versions such as Minecraft 1.19.3 going forward.

**Comment by jackassmc** [comment]
Oh yeah, true, so the major version could stay the same. I can't deal with this on a phone though so I'll look into it more tomorrow or sometime this weekend. If you already have write access here feel free to cut the releases, I trust your judgement.

**Comment by haykam821** [comment]
I don't have write access here. Also, version 5.0.0 was not removed from Maven.

**Comment by Prospector** [comment]
Fixed with a force push on the 1.19 branch (you may have to fix your history locally @jackassmc) and a new branch for 1.19.3. Released 4.1.0 for 1.19.2 and 5.0.0-alpha.1 for 1.19.3
