### ISSUE TITLE
[Feature Request] Customizable per-mod backgrounds

### ISSUE THREAD

**Issue by Mordna** [Prospector/ModMenu#5]
Let mods optionally change the background of the mod menu if it is currently selected, by providing images in a 'background' folder/package near the mod icon

**Why**: 
That could allow mods to provide 'hints' (ex. screenshots of new worlds, entities, blocks...) for the user about the mod without visiting the mod homepage/wiki. Although that would be irrelevant in self-made modpacks or with just a few mods, it would enhance modpacks with tons of mods.

**Comment by Prospector** [comment]
I think I'm gonna say no to this because I like the uniform design. However I have another idea for another mod
