### ISSUE TITLE
[Suggestion] Move Issues & Website Button

### ISSUE THREAD

**Issue by shedaniel** [Prospector/ModMenu#51]
![image](https://user-images.githubusercontent.com/34910653/60383399-a4191f00-9aa2-11e9-82d1-93bfd40b922b.png)

Sorry for my very bad photoshopping skills but I think this can save some space and _honestly it looks good_

**Comment by MrIbby** [comment]
Suggestion for suggestion: Add tooltips that pop up when the user is hovering over the buttons

- `Issues` / `Issue Tracker` / `Bug Tracker`
- `Website`
- `Options` / `Settings` / `Configuration` / `Config`

**Comment by Prospector** [comment]
I do think the current placement isn't ideal, but I think this particular suggestion isn't ideal either as it even further limits the already limited horizontal space.
