### ISSUE TITLE
cant change color

### ISSUE THREAD

**Issue by WideKavin** [Prospector/ModMenu#510]
not a big deal but i would like to change it

it gave this

The game crashed whilst rendering screen
Error: java.lang.ArithmeticException: / by zero

[crash-2022-12-03_22.04.45-client.txt](https://github.com/TerraformersMC/ModMenu/files/10147794/crash-2022-12-03_22.04.45-client.txt)

**Comment by jackassmc** [comment]
This appears to be an issue with the Coordinates Display mod, please report it at [Boxadactle/coordinates-display](https://github.com/Boxadactle/coordinates-display/issues).
