### ISSUE TITLE
Game crashes when pausing via F3+esc

### ISSUE THREAD

**Issue by CalXee** [Prospector/ModMenu#511]
Game crashes on 1.19.3 when modmenu is installed (no other mods, not even fabric api) and pausing via F3+esc. Tested on Mac.

https://pastebin.com/hD3AW6xi

**Comment by jackassmc** [comment]
Fixed in [v5.0.2](https://github.com/TerraformersMC/ModMenu/releases/tag/v5.0.2). Thanks for reporting!
