### ISSUE TITLE
Line feeds don't break lines in the license field.

### ISSUE THREAD

**Issue by nnym** [Prospector/ModMenu#516]
Mod Menu version 5.0.2.

`license` is `"Cloth Config: GNU LGPL v3.0 or later\nsnakeyaml: Apache License 2.0\ntoml4j and Jankson: MIT License"`.

![Screenshot_20221218_013543](https://user-images.githubusercontent.com/44427720/208273033-ae460766-76f1-484e-980f-00b0e947cc13.png)

**Comment by Prospector** [comment]
This is not supported by the [`fabric.mod.json` spec](https://fabricmc.net/wiki/documentation:fabric_mod_json)

> **license** Defines the licensing information. Can either be a single license string or a list of them.
> * This should provide the complete set of preferred licenses conveying the entire mod package. In other words, compliance with all listed licenses should be sufficient for usage, redistribution, etc. of the mod package as a whole.
> * For cases where a part of code is dual-licensed, choose the preferred license. The list is not exhaustive, serves primarily as a kind of hint, and does not prevent you from granting additional rights/licenses on a case-by-case basis.
> * To aid automated tools, it is recommended to use [SPDX License Identifiers](https://spdx.org/licenses/) for open-source licenses.
