### ISSUE TITLE
Incorrect string in the settings menu in English (United Kingdom), "Z-A" instead of "Libraries"

### ISSUE THREAD

**Issue by RomanPro100** [Prospector/ModMenu#538]
## English (United Kingdom):
![image](https://user-images.githubusercontent.com/99795209/216665264-59d96fff-4207-49da-8ca6-a7aa239b2900.png)
![image](https://user-images.githubusercontent.com/99795209/216663706-96ff52cc-7525-4037-8330-adeca2b27a0f.png)

## English (US):
![image](https://user-images.githubusercontent.com/99795209/216665531-a822103c-84c0-4029-920b-85932674be85.png)
![image](https://user-images.githubusercontent.com/99795209/216663933-315c6e6c-5850-4795-87e9-750e74d78826.png)

**Comment by Prospector** [comment]
This has been fixed over on the Crowdin, it should be in an update in the next week or so.
