### ISSUE TITLE
Buttons on the Title Screen get moved around

### ISSUE THREAD

**Issue by Sollace** [Prospector/ModMenu#54]
For some reason buttons are always pushed either up (above the mods button) or down (below the mods button) depending on window size.

One example being the pony button that jumps between positions as you resize the window:
<img src="https://cdn.discordapp.com/attachments/507982478276034570/600696406335946762/unknown.png">
<img src="https://cdn.discordapp.com/attachments/507982478276034570/600696483221864469/unknown.png">

Also less noticeable, the pants button was being moved down. Here's what it's _supposed_ to look like given the positions I specified when adding the buttons:
<img src="https://cdn.discordapp.com/attachments/507982478276034570/600699500289589248/unknown.png">

I had to force them back to their original positions using a future call like this:

      MinecraftClient.getInstance().execute(() -> {
          button.y = y;
      });

I feel like Mod Menu should actually _check_ whether a button is going to overlap before it goes moving everything around.

**Comment by Prospector** [comment]
Where are your buttons supposed to be/where are they without mod menu installed?

**Comment by Sollace** [comment]
Here's a side-by-side comparison.
![image](https://user-images.githubusercontent.com/6429283/61454213-8ed83780-a960-11e9-8fe5-b7c19c2e3f10.png)

This is patched in an update to the mods, just by setting the y position again after adding them.

    private void onScreenInit(Screen screen, ScreenInitCallback.ButtonList buttons) {
        if (screen instanceof TitleScreen) {
            Button button = buttons.add(new Button(screen.width - 50, screen.height - 50, 20, 20));
            ...
            button.y = screen.height - 50; // ModMenu;
        }
    }

But I shouldn't have to do this just to keep my buttons from being messed with.

**Comment by Prospector** [comment]
This is intentional, it is meant to ensure the place you lined your buttons up with is consistent when you install Mod Menu... quite frankly I didn't anticipate anyone who decided *not* to line their buttons up with one of the other buttons...

**Comment by Sollace** [comment]
Ooo...kay.

A bit of a strange decision. It has this weird effect that causes buttons to have an extra gap between them, and messes with any arrangement that depends on the buttons keeping the positioning they were intended to have.

imo. You should rather work on a solution that doesn't end up offsetting the entire Title Screen. (hate to say, Forge had the right idea on something for once)

**Comment by Prospector** [comment]
personally, I find it strange that you would have buttons that don't align at all with the current buttons on the screen

**Comment by Sollace** [comment]
That's because they're designed to align with the bottom-right corner. They're not intended to be the centre of attention like that. Though you do have a point, I've at times found myself looking at how the pants button doesn't quite align with the bottom set of buttons and thought it looked strange.

But when you resize the game window and make it larger, you realise it would look a whole lot weirder to have ot float up next to the regular buttons instead.

**Comment by Prospector** [comment]
I think I'm gonna go ahead and say no to fixing this, because I think the benefit of aligned buttons staying in their positions relative to other buttons vastly outweighs the very niche case of intentionally misaligned buttons (never seen anyone other than you do this). I may, however, consider altering how the buttons are moved...maybe only if they're aligned with a button or a blacklist or something.
