### ISSUE TITLE
Incorrect Button Label

### ISSUE THREAD

**Issue by Obscure2020** [Prospector/ModMenu#549]
### Just updated to this version of Mod Menu on my 1.19.3 instance:
![image](https://user-images.githubusercontent.com/69320464/219662418-dbf1da1f-acc5-4656-953b-db79c2b10273.png)

### I found this in Mod Menu's config menu. That bottom-right button looks pretty messed up.
![image](https://user-images.githubusercontent.com/69320464/219662188-19986a92-9df0-46c6-99b1-8d9c3543bef8.png)

**Comment by Prospector** [comment]
Fixed in 5.1.0-beta.3 which should be out shortly

Edit: https://modrinth.com/mod/modmenu/version/5.1.0-beta.3
