### ISSUE TITLE
Failed to update configs

### ISSUE THREAD

**Issue by Lorelando** [Prospector/ModMenu#55]
Getting this error with mousewheelie, whenever I try to change to config it generates an empty file, but does not write anything.
https://gist.github.com/Lorelando/12ad44c0d2c3699a6e08bac833512325
Moovry posted about it on the mousewheelie Github: https://github.com/Siphalor/mouse-wheelie/issues/20

**Comment by Lorelando** [comment]
Uh, when deleting the empty config file after starting Minecraft (at first it wouldn't let me do it), and then changing to through the menu, it works.

**Comment by Prospector** [comment]
Mod Menu doesn't add any configs, so this issue is on the end of whoever added it.
