### ISSUE TITLE
ModMenu thinks v2.6.10 on Modrinth is newer than v2.6.11 (Also on Modrinth)

### ISSUE THREAD

**Issue by Andre601** [Prospector/ModMenu#550]
ModMenu's update check doesn't seem to be that good or accurate as it tells me that the mod "Fast Load" has a new update available on Modrinth.
The update in question is v2.6.10 (Or `v1.19.3.fabric.2.6.10` as it is shown), which obviosuly isn't newer than 2.6.11 which is installed.

I think ModMenu thinks it's newer because the latest version for the loader (Fabric) is set to 2.6.11, while the previous version is set as `1.19.3.fabric.2.6.10`.

Idk if there would be a fix for this, but perhaps a tool like FlexVer should be used for comparing versions, as it usually is capable of recognizing different version patterns like the above and properly determine if the version is actually new or not.

Screenshot:
![grafik](https://user-images.githubusercontent.com/11576465/219690751-4edd877f-986d-46a5-9c5f-e9c8a873ef6c.png)

**Comment by Prospector** [comment]
Ah, yeah. You're running Quilt and the latest version on Modrinth available for Quilt is 2.6.10. Hmm...

**Comment by Andre601** [comment]
> Ah, yeah. You're running Quilt and the latest version on Modrinth available for Quilt is 2.6.10. Hmm...

Yeah... Idk, it's a bit weird for me. It should still prioritize the version tho imo, even if latest version is only fabric and not quilt.

**Comment by Prospector** [comment]
Going to say this is an issue on Modrinth's end: https://github.com/modrinth/code/issues/2660

**Comment by Andre601** [comment]
Makes sense. I'll close this issue and hope this can be resolved on Modrinth's end.
