### ISSUE TITLE
Crashes when i try to use the drop down menu for mods 1.19.3

### ISSUE THREAD

**Issue by Water0melon** [Prospector/ModMenu#573]
every time i try to use a drop down menu it crashes, this is the error I get. using multi mc btw.
[crash-2023-02-28_23.41.26-client.txt](https://github.com/TerraformersMC/ModMenu/files/10857514/crash-2023-02-28_23.41.26-client.txt)

**Comment by MegaHakkero** [comment]
This is a cloth config API issue, not a Mod Menu issue, as I just found out.
It's caused by a bad version of cloth config API being included with a mod and can be fixed by installing the latest cloth config API for 1.19.3 in your mods folder
