### ISSUE TITLE
【1.19.4】Opening Esc in-game does not display the Mod menu

### ISSUE THREAD

**Issue by zChenX1** [Prospector/ModMenu#576]
Opening Esc in-game does not display the Mod menu
used mod version：modmenu-v6.1.0-rc.1.19.4.cd65565

**Comment by Prospector** [comment]
I can reproduce, thanks for reporting! Investigating...

**Comment by zChenX1** [comment]
> 我可以复制，感谢您的报告！调查。。。
![2023-03-16_17 53 30](https://user-images.githubusercontent.com/94461675/225580692-43f93f49-1947-4b50-8ef1-55d43b46c049.png)
Probably so, the title screen that appears when you click the Esc button in the game does not have a "Mods" button and it is difficult to show only using screenshots

**Comment by Prospector** [comment]
Fixed in 6.1.0-rc.2
