### ISSUE TITLE
Mod menu button disappeared

### ISSUE THREAD

**Issue by Felix14-v2** [Prospector/ModMenu#577]
https://user-images.githubusercontent.com/75726196/225766695-9c173f9b-b385-4592-acc3-f11928904a1d.mp4

[latest.log](https://github.com/TerraformersMC/ModMenu/files/10996348/latest.log)

- 1.19.4
- No other mods

**Comment by Prospector** [comment]
Update Mod Menu

**Comment by Felix14-v2** [comment]
Oh, sorry, I was confused by the featured version

**Comment by Prospector** [comment]
think that was my bad, it was listed as 1.19.4-rc3 instead of 1.19.4

**Comment by Felix14-v2** [comment]
By the way, can you fix this, please? 😄
![image](https://user-images.githubusercontent.com/75726196/225768385-e81daf3e-e4ba-4c5b-9ff0-b56e7dea35f1.png)
