### ISSUE TITLE
Entire mod entry opens config if the mod has submods and config available

### ISSUE THREAD

**Issue by Madis0** [Prospector/ModMenu#578]
v6.1.0-rc4, MC 1.19.4

1. Get a mod that has submods and a config by itself, e.g. [Puzzle](https://www.curseforge.com/minecraft/mc-mods/puzzle)
2. Click on the icon on the mod list - submods get expanded as expected
3. Click on the title/summary on the mod list - mod unexpectedly opens its config

**Comment by Prospector** [comment]
Seems like this got fixed somehow in the upcoming build. Went to go fix it and the bug was gone lol
