### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by UsernameAdamGits** [Prospector/ModMenu#580]
Every time I open up Minecraft and click on the mods button, it just crashes??? I don't know what I'm doing wrong here.
Version : 1.19.4 Fabric
I used the latest version of the mod for this, which is apparently made for 1.19.3.
[crash-2023-03-19_16.06.50-client.txt](https://github.com/TerraformersMC/ModMenu/files/11011760/crash-2023-03-19_16.06.50-client.txt)

**Comment by haykam821** [comment]
The latest version for Minecraft 1.19.4 is [version 6.1.0 release candidate 4](https://github.com/TerraformersMC/ModMenu/releases/tag/v6.1.0-rc.4). You are using version 5.0.2.
