### ISSUE TITLE
game crashes, when another mod adds a GridWidget/GridLayout to the pause menu, on 6.1.0-rc.4 1.19.4

### ISSUE THREAD

**Issue by fayer3** [Prospector/ModMenu#582]
when another mod adds a GridWidget/GridLayout to the pause menu the game crashes, because of a failed cast

as an example, of a mod that does that, we with vivecraft do it, to get two buttons in one button slot.

latest log: 
[latest.log](https://github.com/TerraformersMC/ModMenu/files/11017667/latest.log)

crash report: 
[crash-2023-03-20_13.16.22-client.txt](https://github.com/TerraformersMC/ModMenu/files/11017672/crash-2023-03-20_13.16.22-client.txt)

**Comment by fayer3** [comment]
this worked fine in 1.19.3 btw

**Comment by fayer3** [comment]
affected code https://github.com/TerraformersMC/ModMenu/blob/acc51dfb6be35e392adb40fb4eda180b556225a8/src/main/java/com/terraformersmc/modmenu/mixin/MixinGameMenu.java#L40
doing a simple typecheck before the cast should prevent the crash
for the moving of stuff you can cast to `Widget` instead I think.

**Comment by lmore377** [comment]
By any chance can you provide a jar file with this fix? I'm not familiar with compiling java lol

**Comment by Prospector** [comment]
Will be releasing a fix shortly, fixed in [d8daccd](https://github.com/TerraformersMC/ModMenu/commit/d8daccda04d0a3ac5bed072dd8ca4bf9e8df504d)
