### ISSUE TITLE
How to hide the mod you want?

### ISSUE THREAD

**Issue by Sorotsu1** [Prospector/ModMenu#586]
How to hide the mod you want?

**Comment by Felix14-v2** [comment]
![image](https://user-images.githubusercontent.com/75726196/229322809-3f93ac14-ead7-4783-bfcd-5bc10cd5305c.png)

**Comment by Sorotsu1** [comment]
а где это?
Where is it?

**Comment by Felix14-v2** [comment]
> а где это?

`.minecraft/config/modmenu.json`
В этот массив нужно вписать идентификаторы модов, соблюдая синтаксис json. Идентификатор можно посмотреть путём наведения курсора мыши на название мода в ModMenu либо вручную внутри мода, в файле fabric.mod.json
![image](https://user-images.githubusercontent.com/75726196/229354174-14bf412d-f414-49af-b381-76fead280216.png)

**Comment by Prospector** [comment]
Looks like you got it figured out
