### ISSUE TITLE
Update checker prompts to update to Beta and Alpha versions

### ISSUE THREAD

**Issue by Ryoya15** [Prospector/ModMenu#604]
The Update checker will prompt for an update if it is newer than the current mod version, even if it is a Beta or Alpha version.
It should either inform only about the stable version or clearly state that it is a Beta or Alpha version.
![スクリーンショット 2023-05-26 173611](https://github.com/TerraformersMC/ModMenu/assets/111482921/4e89ea28-7cc8-46a2-93b6-df05b01c8da4)

**Comment by SecT0uch** [comment]
For more context, I think this happens with [fabric-api](https://modrinth.com/mod/fabric-api)

**Comment by Ryoya15** [comment]
It also happens with other mods such as [Sodium Extra](https://modrinth.com/mod/sodium-extra).
