### ISSUE TITLE
Minecraft crashes with an error I don't understand

### ISSUE THREAD

**Issue by Denyginod** [Prospector/ModMenu#605]
I'll attach a crash report below, I tried to update java and mods, I don't know what the problem is. I searched the whole Internet
[crash-2023-06-02_11.52.30-client.txt](https://github.com/TerraformersMC/ModMenu/files/11632730/crash-2023-06-02_11.52.30-client.txt)

**Comment by Denyginod** [comment]
I just click the network game button

**Comment by haykam821** [comment]
This issue appears to be related to the Skin Swapper mod according to the stack trace. There is an issue open on their issue tracker already: cobrasrock/Skin-Swapper#51.
