### ISSUE TITLE
The latest "WTHIT" mod is running on Quilt，the Mod Menu update detect wrong think is the latest version for Fabric.

### ISSUE THREAD

**Issue by ghost** [Prospector/ModMenu#606]
![image](https://github.com/TerraformersMC/ModMenu/assets/110441378/8b3e9689-4c70-4cb3-93f9-3e1319d17e7b)

**Comment by sylv256** [comment]
I believe this is due to it not recognizing Quilt versions and not recognizing Quilt as a mod loader.
Drama time? /j

**Comment by pointydev** [comment]
Can also reproduce using Cherished Worlds `quilt-6.1.0+1.20.1`, Mod Menu `7.1.0` and Quilt `0.19.1`, with the latest version of Cherished Worlds on Modrinth for Fabric being `fabric-6.1.0+1.20.1`.
![example](https://the.yog.zone/A8NcCZa.png)

**Comment by ghost** [comment]
> Can also reproduce using Cherished Worlds `quilt-6.1.0+1.20.1`, Mod Menu `7.1.0` and Quilt `0.19.1`, with the latest version of Cherished Worlds on Modrinth for Fabric being `fabric-6.1.0+1.20.1`. ![example](https://camo.githubusercontent.com/1e0fede748ae4977998e9a56cc53cbb01e7bf92dacd00098f51911b6ea418ca3/68747470733a2f2f7468652e796f672e7a6f6e652f41384e63435a612e706e67)

I have a suspicion that the Mod Menu cannot recognize the Quilt version of Mods!That's why it's like this!
