### ISSUE TITLE
[MC 1.20] Mods Button not showing?

### ISSUE THREAD

**Issue by mk-pmb** [Prospector/ModMenu#609]
Hi! Thanks for ModMenu! In MC 1.19.4 with ModMenu 6.1.0-rc.4 it was super easy to access it, it added a "Mods" button to the main menu and the pause menu. Now I'm playing a 1.20 modpack that includes ModMenu 7.0.1, and I verified the JAR is the same as on [the release page](https://github.com/TerraformersMC/ModMenu/releases/tag/v7.0.1), at least they have the same SHA-512.

However, I was unable to find the Mods button anymore. I disabled all other mods to make sure it's not a conflict, but still no trace. [Screenshot of my main menu.](https://abload.de/img/modmenu_button_wherenbd08.jpeg)

MultiMC's "Minecraft Log" (where all the Java messages are collected) does not contain the word "ModMenu" (letter case ignored). How can I start debugging this?

**Comment by haykam821** [comment]
Just to make sure, is Fabric loader installed in your instance? From the screenshot you've shown, it looks like the loader isn't installed so no mods are running.

**Comment by mk-pmb** [comment]
Thanks for reminding me. I had assumed a mod pack that comes with lots of Farbic mods, would have included the Fabric loader. I also assumed MultiMC would have warned when using loader mods without a loder. Sorry for having wasted your time.
Update: Now with Fabric API installed ([tutorial](https://fabricmc.net/wiki/player:tutorials:install_multimc:windows)), it works as expected.
