### ISSUE TITLE
Missing Translations!

### ISSUE THREAD

**Issue by Amirhan-Taipovjan-Greatest-I** [Prospector/ModMenu#628]
The [Crowdin Project](https://crowdin.com/project/mod-menu/discussions/3) doesn't have these strings (compare with this: https://github.com/TerraformersMC/ModMenu/blob/1.20/src/main/resources/assets/modmenu/lang/en_us.json):

"option.modmenu.quick_configure", "option.modmenu.quick_configure.true", "option.modmenu.quick_configure.false".

So they should appear in that project too.

**Comment by Prospector** [comment]
The crowdin is sadly a mess, I really don't like nor really understand how it works. I may have to end up shutting it down and just accept translations via PRs again since I don't really have time to figure it out

**Comment by Amirhan-Taipovjan-Greatest-I** [comment]
> The crowdin is sadly a mess, I really don't like nor really understand how it works. I may have to end up shutting it down and just accept translations via PRs again since I don't really have time to figure it out

Then should I make ASAP PR with tranlsation?

**Comment by Prospector** [comment]
sure, if you'd like!

**Comment by Amirhan-Taipovjan-Greatest-I** [comment]
> sure, if you'd like!

Then I need more explanation what "Quick Configure" does.

**Comment by LostLuma** [comment]
It allows double clicking on a mod to open its config screen without having to hit the config button on the right hand side.

**Comment by Amirhan-Taipovjan-Greatest-I** [comment]
> It allows double clicking on a mod to open its config screen without having to hit the config button on the right hand side.

Ok, then check this -> #634
