### ISSUE TITLE
trying to find source of recent runtime crashing, however it appears to be inconsistent 

### ISSUE THREAD

**Issue by notandvm** [Prospector/ModMenu#648]
as of the sodium 0.5 update, when used within my modpack, opening mod menu leads to a 2 second freeze followed by hard crash:

> [hs_err_pid1450.log](https://github.com/TerraformersMC/ModMenu/files/12337073/hs_err_pid1450.log)

disabling all mods within the pack related to sodium fixes the issue (all are the latest version at the time of writing)

in my case these mods would be:
* _sodium (& sodium extra, reese's sodium options)_
* _sodium shadowy path blocks_
* _indium_
* _iris_

_however_, when launching mod menu with only these mods, it functions perfectly fine - no crash whatsoever
i've attempted cross-referencing with other crash logs posted here assuming it was a specific mod's issue, and enabling shared mods between posted logs' mods and my own mods to try and narrow it down but no crashes had occured

has anyone else had success so far finding a specific culprit that causes the crash?

**Comment by enderprism** [comment]
+1, can confirm.
here's a log with these mods only, at their latest versions at the moment of writing:
- Fabric API
- Indium
- Iris
- Mod Menu
- Reese's Sodium Options
- Sodium Extra
- Sodium

[i9DHATZ.txt](https://github.com/user-attachments/files/21930525/i9DHATZ.txt)

**Comment by enderprism** [comment]
This is caused by YACL and referenced in this issue, so this one can be closed:
https://github.com/isXander/YetAnotherConfigLib/issues/101
