### ISSUE TITLE
The Mod Menu Button doesn't show up

### ISSUE THREAD

**Issue by HeadHunter4410** [Prospector/ModMenu#65]
Hi! So the Mod Menu Button doesn't show up for me in minecraft and I really don't know what to do. I installed fabric and the other stuff but it just doesn't work. 
![Unbenannt](https://user-images.githubusercontent.com/54729651/64057441-23a79500-cb9d-11e9-8af3-d35fc9e40e08.PNG)
![Unbenandant](https://user-images.githubusercontent.com/54729651/64057459-4e91e900-cb9d-11e9-9dd4-ac399a5e83b6.PNG)

**Comment by Prospector** [comment]
Can you send me a log?

**Comment by HeadHunter4410** [comment]
Im sorry but Im now using forge for the mods and other stuff. Im really sorry and also I don't really know how to show you the log because Im a piece of trash.
