### ISSUE TITLE
Integrating ModMenu into Fabric/Quilt

### ISSUE THREAD

**Issue by Quizer9O8** [Prospector/ModMenu#684]
Ever since the birth of ModMenu I've been wondering why it isn't a part of Fabric and Quilt yet.
As far as I know Forge has a built-in modmenu since its inception.
Are there any plans to integrate Modmenu in Fabric and Quilt and if not why?

**Comment by Prospector** [comment]
You'd have to ask them that, I don't make Fabric or Quilt
