### ISSUE TITLE
Mods button does not appear when using 'Lunar Client' modpack

### ISSUE THREAD

**Issue by kloppie74** [Prospector/ModMenu#692]
hii! Do you guys also supporrt lunar client mods? You can add your own mods but cant access the mod menu :(

**Comment by DarkFireNinja** [comment]
@kloppie74 

> hii! Do you guys also supporrt lunar client mods? You can add your own mods but cant access the mod menu :(

You cant add mods to lunar client. This has nothing to do with Modmenu.

**Comment by kloppie74** [comment]
You actual can, search on yt how to add mods to lunar client

**Comment by Prospector** [comment]
if Mod Menu doesn't work on Lunar that is their fault not mine
