### ISSUE TITLE
Update checker does not recognize that mods are outdated

### ISSUE THREAD

**Issue by NolanHewitt** [Prospector/ModMenu#694]
Around a week ago the update checker stopped working. Not sure if this is something caused by a backend change on the side of modrinth or something else.

**Comment by APTX4869AP** [comment]
我也遇到同样问题，

**Comment by haykam821** [comment]
The underlying issue is indeed on Modrinth's side; modrinth/theseus#1045 can be used to track the issue. Since the API is just masquerading the response as if no mods need updates, Mod Menu cannot do anything to solve the issue. I'll keep this issue open until the underlying issue is resolved.

**Comment by memphismc** [comment]
so its up to modrinth to fix this? have you guys reached out to them?

**Comment by gniftygnome** [comment]
Yes

**Comment by haykam821** [comment]
The underlying issue seems to be resolved as per an announcement [in the Modrinth Discord announcements channel](https://discord.com/channels/734077874708938864/734084055225597973/1210076585542160424).
