### ISSUE TITLE
Update checker recommand me an earlier version when I'm using a version later than the latest version on modrinth.

### ISSUE THREAD

**Issue by NoNameTeam-NoNamer** [Prospector/ModMenu#695]
# Update checker recommand me an earlier version when I'm using a version later than the latest version on modrinth.
![image](https://github.com/TerraformersMC/ModMenu/assets/157032812/ec5743ec-36a0-426a-9b73-5d08b9333d4b)
Like this,I installed this mod **5.3.8** from causeforge,but its latest version on modrinth is **5.3.5**
~~It's stupid~~ 🤣 

Minecraft version:1.20.4
Mod Menu version:9.0.0 for 1.20.4

**Comment by NoNameTeam-NoNamer** [comment]
I checked,maybe because the **5.3.8** is for 1.20.1...

**Comment by Prospector** [comment]
Yup, 5.3.5 is the latest version for 1.20.4 according to the author's Modrinth page https://modrinth.com/mod/ambientsounds/versions?g=1.20.4
