### ISSUE TITLE
The game crashed whilst rendering overlay

### ISSUE THREAD

**Issue by VinnieTeix** [Prospector/ModMenu#702]
Hello,
I get this error code trying to run the ModMenu on Fabric for MC 1.20.4

```
The game crashed whilst rendering overlay
Error: java.lang.IncompatibleClassChangeError: class com.terraformersmc.modmenu.gui.widget.ModMenuButtonWidget overrides final method net.minecraft.class_339.method_25394(Lnet/minecraft/class_332;IIF)V
Exit code: -1
```

These are the mods that I run:

- auto-clicker-fabric-84.0.0.jar
- continuity-3.0.0-beta.4+1.20.2.jar
- 130842 easiervillagertrading-1.20-fabric0.83.0-1.5.4.jar
- 2160893 fabric-api-0.96.4+1.20.4.jar
- indium-1.0.30+mc1.20.4.jar
- iris-mc1.20.4-1.6.17.jar
- mc.v1.20.x-quick_hotkeys-1.0.2_fabric.jar
- 1mobhealthbar-fabric-1.20.x-2.3.0.jar
- modmenu-7.2.1.jar
- sodium-fabric-0.5.8+mc1.20.4.jar
- voicechat-fabric-1.20.4-2.5.8.jar

Thanks in advance for any help!

**Comment by haykam821** [comment]
Your Mod Menu version is very outdated for Minecraft 1.20.4. You should use [version 9.0.0](https://github.com/TerraformersMC/ModMenu/releases/tag/v9.0.0) instead.

**Comment by VinnieTeix** [comment]
> Your Mod Menu version is very outdated for Minecraft 1.20.4. You should use [version 9.0.0](https://github.com/TerraformersMC/ModMenu/releases/tag/v9.0.0) instead.

Thanks, I downloaded it from a requirement list of another mod and didn't notice.
