### ISSUE TITLE
Game crashes when scrolling down the modmenu

### ISSUE THREAD

**Issue by E0x72-21** [Prospector/ModMenu#718]
crash report: https://mclo.gs/Yf3BPhC
all mods that run on the client:
![image](https://github.com/TerraformersMC/ModMenu/assets/85837864/edac2df0-dc08-4866-b3d4-6b365fd5a4b4)

Thanks in advance for any help

**Comment by haykam821** [comment]
This issue seems like a duplicate of #693, where the issue comes from an external mod specifying a badge that doesn't exist. I will change the behavior to log a warning specifying the mod rather than crash the game.
