### ISSUE TITLE
Opening Mods list causes huge memory spike

### ISSUE THREAD

**Issue by SnipUndercover** [Prospector/ModMenu#727]
Hi! I'm relatively new to modded Minecraft and I'm not sure whether this is the right outlet to report such an issue.

Opening the mods menu with around 44 mod `.jar`s causes Minecraft to freeze, following a **massive, more than three-fold increase** in memory usage.

The following screenshots are taken while opening the menu in the title screen.
Before:
![Memory usage before opening Mods menu: around 2700 MB](https://github.com/TerraformersMC/ModMenu/assets/49392266/511e3860-2bc3-414c-9daf-e1c62500cb73)

After:
![Memory usage after opening Mods menu: around 9200 MB](https://github.com/TerraformersMC/ModMenu/assets/49392266/5d65047c-b434-4fad-92da-5facb733a196)

After Minecraft unfreezes and the memory spike is over, the JVM seems allocate 1GB more than before, idling at 3664 MB compared to 2693 MB.
If allowed to reach the memory cap, the freeze and memory spike will take longer.
*(The client has access to 8 GB of ram via `-Xmx8G`; I have 32 GB installed)*

On one occasion I have managed to cause Minecraft to crash due to a lack of available memory, but I cannot reproduce this again.
Here's the [crash log](https://github.com/TerraformersMC/ModMenu/files/15195443/crash-2024-05-03_02.24.19-server.txt) if it's of any use.

**Comment by notrohit1702** [comment]
I haven't been able to properly check the memory usage, but I can confirm that for me, it takes a bit of time for Mod Menu to load, 97 mods, Mod Menu version 11.0.2 on Fabric 1.21.1.

**Comment by gniftygnome** [comment]
What if you edit the config (something like `config/modmenu.json`) and set `update_checker` to `false`?

**Comment by notrohit1702** [comment]
> What if you edit the config (something like `config/modmenu.json`) and set `update_checker` to `false`?

I've turned that off and it still takes a bit of time to load.

**Comment by LostLuma** [comment]
It's probably because ModMenu eagerly creates all config screens when opening the mods screen:
https://github.com/TerraformersMC/ModMenu/blob/51c25d30d67fa66ef73d8dc478a121ce29183c72/src/main/java/com/terraformersmc/modmenu/gui/ModsScreen.java#L104-L110

**Comment by notrohit1702** [comment]
> It's probably because ModMenu eagerly creates all config screens when opening the mods screen:
> 
> https://github.com/TerraformersMC/ModMenu/blob/51c25d30d67fa66ef73d8dc478a121ce29183c72/src/main/java/com/terraformersmc/modmenu/gui/ModsScreen.java#L104-L110

Is there any way to counteract this lag?

**Comment by LostLuma** [comment]
Probably. I may look into it in a few hours.
