### ISSUE TITLE
library badge problem

### ISSUE THREAD

**Issue by drkhodakarami** [Prospector/ModMenu#732]
Hi, I am using 10.0.0-beta.1 version. When I add library badge to the array, the entry for the mod is completely gone and my mod won't show in the list. The deprecated (just for testing) works properly. But the library has a problem. Not sure if the mod itself needs to have special setup or not, was just trying the badges as a test.

**Comment by Prospector** [comment]
it should show if you show libraries? by default libraries are hidden
