### ISSUE TITLE
Update checker says that a new version of Mod Menu is available, but I have already a newer one.

### ISSUE THREAD

**Issue by gegentan** [Prospector/ModMenu#735]
Update checker says that a new version is available (Mod Menu 9.0.0), but I have Mod Menu v9.2.0-beta.2 already installed

![image](https://github.com/TerraformersMC/ModMenu/assets/120120135/3f3b775f-806c-4ce0-b456-36c4e00ded66)

**Comment by gegentan** [comment]
Same for other mods

![image](https://github.com/TerraformersMC/ModMenu/assets/120120135/93563be7-4e94-4abf-989a-e333f0421d19)

**Comment by gegentan** [comment]
Changing "Update Channel" to "All" in Mod Menu setting helped.

**Comment by haykam821** [comment]
Duplicate of #714
