### ISSUE TITLE
Mod Isn't working.

### ISSUE THREAD

**Issue by Shrek-vr** [Prospector/ModMenu#737]
So I'm using version 10.0.0-beta.1 and the mod isn't working for me. I don't see a button to look at all my mods like I usually do, it says the mod works for version 1.20.6 but it isn't. I've tried deleting the mod and retrying it and it still doesn't work. Can someone help?

**Comment by haykam821** [comment]
Could you [upload a game log](https://fabricmc.net/wiki/player:tutorials:logs)?

**Comment by Shrek-vr** [comment]
Uh, how do I do that?

**Comment by Shrek-vr** [comment]
https://gist.github.com/Shrek-vr/e201602e70d894c8aefa26f2bd117269 Does this work? I tried to figure it out so I hope this is right

**Comment by haykam821** [comment]
The mod doesn't seem to be loading at all in your case. How are you downloading and installing the mod? If you are installing the mod manually, the mod file should be placed directly into the `mods` directory without being renamed.

**Comment by Shrek-vr** [comment]
I downloaded the mod a few times from both modrinth and curseforge. After I downloaded the .jar file for modmenu 10.0.0-beta.1 I instantly took it from downloads and put it into my 1.20.6 mods folder directory thing. That is how I've always done my mods and they usually work fine.

**Comment by girloffthecob** [comment]
I'm having the same issue, did the same thing as you, put it into my mods folder and opened Fabric 1.20.6, I installed the fabric API as well... has anyone solved this yet?

**Comment by Shrek-vr** [comment]
I solved it. I used the official fabric loader instead of the Iris Shaders fabric loader
