### ISSUE TITLE
Some mod options missing

### ISSUE THREAD

**Issue by asimard1** [Prospector/ModMenu#738]
Mod menu only shows some mods, while some have config files and won't show up. Those include all mods for which the config file is a .toml.

**Comment by Jab125** [comment]
Not all mods provide configuration screens.
Mod Menu just creates a mod menu, it does not create configuration screens for you.

**Comment by Prospector** [comment]
These are up to the mods themselves to provide, Mod Menu currently does not provide this

**Comment by asimard1** [comment]
Oh I see, thank you
