### ISSUE TITLE
Minecraft 1.20.6 Copyright text now a private member

### ISSUE THREAD

**Issue by schneiderchristopher** [Prospector/ModMenu#741]
Apparently, Mojang decided to make `TitleScreen.COPYRIGHT` a private member, so this https://github.com/TerraformersMC/ModMenu/commit/3a713a1e576d4b52bde20a0bc99f785673bb6e86 does not work anymore.

I could do a PR but I'm not very familiar with the project, I believe this is a quick fix.

Here's some of the log:
```
Time: 2024-06-10 17:20:07
Description: Rendering overlay

java.lang.IllegalAccessError: class com.terraformersmc.modmenu.event.ModMenuEventHandler tried to access private field net.minecraft.client.gui.screen.TitleScreen.COPYRIGHT 
```

**Comment by Prospector** [comment]
Not sure what you're talking about, are you trying to run the 1.18.2 version of Mod Menu on 1.20.6?
