### ISSUE TITLE
Crashing in 1.21

### ISSUE THREAD

**Issue by nmills3** [Prospector/ModMenu#743]
With only mod menu 11.0.0-beta.1 installed the game keeps crashing during world generation.
Here's a copy of the crash log
[crash-2024-06-14_08.53.01-server.txt](https://github.com/user-attachments/files/15834703/crash-2024-06-14_08.53.01-server.txt)

**Comment by brunohpaiva** [comment]
Had the same issue. This occurs only when Fabric API is not standalone installed (only occurs with the jar-in-jar modmenu's fabric api).

As a temporary workaround, installing Fabric API version `0.100.1+1.21` solves this. Logs: https://api.mclo.gs/1/raw/H4OKg5o

**Comment by sakura-ryoko** [comment]
It's primarily because ModMenu was compiled with a previous version of Fabric API, so the jar-in-jar version is outdated...

**Comment by Prospector** [comment]
Mod Menu for 1.21 is now out
