### ISSUE TITLE
ModMenu Chinese localization doesn't work in 1.21

### ISSUE THREAD

**Issue by wifi-left** [Prospector/ModMenu#744]
![image](https://github.com/TerraformersMC/ModMenu/assets/63381531/dc94250b-d814-4edb-8d23-f6954eee2e57)
As shown in the figure, the translation of the mod is not shown. I checked zh_cn.json in the jar file and it is fine.
Mod version: `modmenu-11.0.0-rc.2`

**Comment by wifi-left** [comment]
I also tested `modmenu-11.0.0-beta.2.jar`.
It works fine.
![image](https://github.com/TerraformersMC/ModMenu/assets/63381531/1d3867c7-a9ac-4a79-a4bb-c84ff89c6e9a)

**Comment by wifi-left** [comment]
I tried to copy the translation file of `modmenu-11.0.0-beta.2.jar` into `modmenu-11.0.0-rc.2` and it worked fine.
![image](https://github.com/TerraformersMC/ModMenu/assets/63381531/d8458c0b-8a15-4d97-8a3c-bfb9d4be281a)

**Comment by Prospector** [comment]
Fixed in RC3, the json was missing a comma. Thanks for the report!

**Comment by Prospector** [comment]
make that RC4, had an issue with RC3
