### ISSUE TITLE
Mods button isn't shown if server has Server Links

### ISSUE THREAD

**Issue by w26ad** [Prospector/ModMenu#745]
Mods button isn't shown if server has Server Links enabled

Steps to reproduce:
1. Install Mod Menu for 1.21
2. Join any server which has Server Links enabled (e.g. Hypixel)
3. See that Mods button isn't shown

![2024-06-16_15 38 16](https://github.com/TerraformersMC/ModMenu/assets/65756919/bf6d14b2-0223-446c-8573-57dc12717fe5)

**Comment by mr-dexter-ssj** [comment]
That's true, even when the mod button's placement is set to icon or under bugs
