### ISSUE TITLE
1.20.4 update issue

### ISSUE THREAD

**Issue by Anonyku05** [Prospector/ModMenu#750]
Basically, on 1.20.4 i have an update issue where the mod menu shows the 9.2.0 beta 2 update available, but when i install it, it shows me  the old version 9.0.0 as an available update, wanted to know if it's gonna be fixed or in the case that the 1.20.4 is no longer supported is there any way to disable the update checker for the mod menu itself

**Comment by Prospector** [comment]
Just pushed v9.2.0 which should contain a backport of this fix. Let me know if it works!

**Comment by Anonyku05** [comment]
It's working fine, thank you !
