### ISSUE TITLE
Lunar Client v1.21 Crash

### ISSUE THREAD

**Issue by tobezdev** [Prospector/ModMenu#754]
Is there an update on the crash for Lunar Client v1.21 when pressing `esc`?
I've contacted Lunar Support and they say that the client is fully compatible, and that the crash is the result of something in the mod.
It's annoying because I have a few mods that depend on Mod Menu for customisation.

Thanks.

**Comment by Prospector** [comment]
No one has ever sent me an actual crash report, but it doesn't happen without Lunar and Lunar isn't something I support, so it's on them. If someone can get me a crash log, I can look into it and see if there's something small I can do about it, but my recommendation is to not use Lunar if it breaks mods.

**Comment by tobezdev** [comment]
I'll provide a crash log in a moment, let me re-create it.

**Comment by tobezdev** [comment]
Crash Log Gist: 
     https://gist.github.com/tobezdev/1025b96c3fb7cd3aae4cc9d18c923e86

CDN Link to download a zipped version of my Fabric 1.21 mods folder: 
     https://tobezdev.hrzn.pics/2LjFc7PD.zip

**Comment by Bonks03** [comment]
To add some context here, as I have tried to post on Lunar subreddit to no avail, there is a button on the title screen for the mod menu which works fine. Furthermore, if you set a keybind for mod menu you can access it while in game, but if you click `esc` it instantly crashes. I have tried every option of how the button shows up in the `esc` menu but it still crashes. Cheers.

**Comment by Bonks03** [comment]
I dont know if this is allowed, so delete if you see fit, but a kind fellow who is also forking some of masa's and updating to 1.21 has forked this ([https://github.com/sakura-ryoko/ModMenu]) and his version does not seem to have this issue

**Comment by Prospector** [comment]
Not sure what you mean, that fork has no changes from my repo.

**Comment by sakura-ryoko** [comment]
> I dont know if this is allowed, so delete if you see fit, but a kind fellow who is also forking some of masa's and updating to 1.21 has forked this ([https://github.com/sakura-ryoko/ModMenu]) and his version does not seem to have this issue

Her *  And my repo I only use to help me port other mods that depend upon ModMenu.
I've given a PR back for 1.21-pre.2  for Prospector, so it only tracks the official changes, or for snapshots that break ModMenu; so I can continue coding.  Once those "snapshots" are outdated, they get deleted.

There shouldn't be anything that is seen as otherwise.

**Comment by sakura-ryoko** [comment]
Also, in terms of your Crash Log, the initial error is caused by Lunar not being compatible with Sodium.
There are no ModMenu related crash traces, it's all Lunar's fault changing all kinds of "things" in the Client that makes it incompatible with many mods.

Sodium will not make changes to support Lunar, as they have no desire to do so.

**Comment by tobezdev** [comment]
> Also, in terms of your Crash Log, the initial error is caused by Lunar not being compatible with Sodium. There are no ModMenu related crash traces, it's all Lunar's fault changing all kinds of "things" in the Client that makes it incompatible with many mods.
> 
> Sodium will not make changes to support Lunar, as they have no desire to do so.

I'll contact Lunar with this information and see what they say. Thanks for debugging the log, I'm useless at it 😭

**Comment by Bonks03** [comment]
> > I dont know if this is allowed, so delete if you see fit, but a kind fellow who is also forking some of masa's and updating to 1.21 has forked this ([https://github.com/sakura-ryoko/ModMenu]) and his version does not seem to have this issue
> 
> 
> 
> Her *  And my repo I only use to help me port other mods that depend upon ModMenu.
> 
> I've given a PR back for 1.21-pre.2  for Prospector, so it only tracks the official changes, or for snapshots that break ModMenu; so I can continue coding.  Once those "snapshots" are outdated, they get deleted.
> 
> 
> 
> There shouldn't be anything that is seen as otherwise.

My apologies. I have no clue why yours works and Prospector's does not. Very strange

**Comment by sakura-ryoko** [comment]
> My apologies. I have no clue why yours works and Prospector's does not. Very strange

The code should be identical to the official.

**Comment by Prospector** [comment]
The difference is they're probably using an older version of your fork, before a bunch of bugfixes happened. It's likely one of the bugfixes touches something like Server Links that Lunar decides to mess with.
