### ISSUE TITLE
Mod list button always says 38 Loaded

### ISSUE THREAD

**Issue by 4techguns** [Prospector/ModMenu#78]
![image](https://user-images.githubusercontent.com/42378704/68753339-6941fe80-05df-11ea-8dec-c4a18530f6e8.png)
The mod list button always says 38 Loaded, regardless of how many mods are there.

**Comment by macaquinyho** [comment]
Mine always shows 31

**Comment by Prospector** [comment]
That's...weird. So if you add or removes mods it is still 38?

**Comment by macaquinyho** [comment]
Actually I was wrong, It's if it started at 30+modmenu and then it just works normal
![Anotación 2019-12-14 225951](https://user-images.githubusercontent.com/14185777/70855140-01285600-1ec6-11ea-8b22-6fcecdf68d3a.png)

**Comment by Prospector** [comment]
Click that filter icon and then you can turn on the displaying of libraries which will show you all 32 mods loaded. Fabric itself has ~30 different modules. I'm guessing this issue is user error

**Comment by macaquinyho** [comment]
When I click on libraries, it only shows 2 new libraries
![Anotación 2019-12-14 231430](https://user-images.githubusercontent.com/14185777/70855210-82ccb380-1ec7-11ea-9084-0aaa30bfd0e6.png)

**Comment by Prospector** [comment]
See how Fabric API has a little 27 next to it? That's a stack of 27 child mods. If you hover over it an arrow should appear and you can expand it to show all of them.

**Comment by macaquinyho** [comment]
Didn't notice lol. Sorry for wasting your time
