### ISSUE TITLE
Include open source license information in mod menu

### ISSUE THREAD

**Issue by liach** [Prospector/ModMenu#80]
https://developers.google.com/android/guides/opensource

This would allow people to comply with the rules set forth by the mods better; and with the inclusion of such info we can be more professional than a lot of android apps :trollface:

Anyways shouldn't be too hard given we already have license info in mod json.

**Comment by modmuss50** [comment]
whats that link got to do with this?

**Comment by liach** [comment]
That link is just a reference that softwares should include open source licenses, especially given that many fabric mods are free open source software.

**Comment by liach** [comment]
Fantastic, thank you!

**Comment by Prospector** [comment]
Only took over a year :P
