### ISSUE TITLE
Crash when trying v12.0.0-beta.1 for 1.21.2-pre3 on 1.21.4-pre1

### ISSUE THREAD

**Issue by vico93** [Prospector/ModMenu#801]
I tried just for curiosity putting ModMenu on a test installation with Fabric 0.16.9 for 1.21.4-pre4. Trying to click on "Mods" button on the main menu crashes the game.

[Crash report](https://gist.github.com/vico93/2334e32c9f557cdbcd60ab73efc2c2df)

**Comment by sakura-ryoko** [comment]
https://github.com/TerraformersMC/ModMenu/pull/802

**Comment by vico93** [comment]
Closed by #802. Thanks a lot for the PR @sakura-ryoko !
