### ISSUE TITLE
Mod Menu somehow identifies Minecraft as a mod of itself

### ISSUE THREAD

**Issue by Sollace** [Prospector/ModMenu#81]
<img src="https://cdn.discordapp.com/attachments/507982478276034570/652154443864997910/unknown.png"></img>

Could it not at least have a [website] and [issues] link to the minecraft.net and the bugtracker?

An option to hide non-mod entries would be good as well.

**Comment by modmuss50** [comment]
I dont think this is an issue. Loader makes MC a mod no real reason to hide it.
