### ISSUE TITLE
Mod update checker

### ISSUE THREAD

**Issue by Madis0** [Prospector/ModMenu#84]
- Uses Curseforge API to check current mods' new releases for launched game version 
- Checks once per game session 
- If there are updates, show the Realms 🔷 icon on mod list button 
- Checks for stable releases by default, option to use beta/alpha too 
- "Update" badge on mods that have updates 
- A button "Update mod" on the mod detail view that directly links to latest JAR on Curseforge

**Comment by Sollace** [comment]
To note:
- Not all mods use curseforge
- Nor all modders like curseforge

It would be beneficial to allow mods to specify their own location, or their own maven (MineLP/HDSkins/Mson all have one) for discovering updates.

**Comment by TheBrokenRail** [comment]
Idea, mod specifies an "update strategy" of which there are multiple builtin in their ```fabric.mod.json```.

Maven:
```json
{
    "custom": {
        "modMenu:updateStrategy": {
            "type": "maven",
            "mavenGroup": "com.example",
            "mavenArtifact": "mod"
        }
    }
}
```

CurseForge:
```json
{
    "custom": {
        "modMenu:updateStrategy": {
            "type": "curseforge",
            "curseforgeSlug": "example"
        }
    }
}
```
GitHub Releases:
```json
{
    "custom": {
        "modMenu:updateStrategy": {
            "type": "github",
            "githubRepo": "example/me"
        }
    }
}
```

```versionRegExp``` is an optional property in ```modMenu:updateStrategy```, ModMenu would determine the latest version by picking the latest version that matches this RegExp.

**Comment by TheBrokenRail** [comment]
```versionRegExp``` would be useful for ```maven``` or ```github``` when the latest version might be for a different MC version, while ```curseforge``` could automatically check.

**Comment by shedaniel** [comment]
This is out of scope for modmenu imo, though modmenu _could_ provide hooks for other mods to do that.

**Comment by paz** [comment]
it only makes sense for mod menu to do this

**Comment by TheBrokenRail** [comment]
My proposal has been implemented in https://gitea.thebrokenrail.com/TheBrokenRail/ModUpdater.git and will be listed on CurseForge at https://www.curseforge.com/minecraft/mc-mods/modupdater when approved.

**Comment by DragonEggBedrockBreaking** [comment]
Btw, Modrinth exists now, so that's one more source you (probably) have to add an option/api for...

**Comment by Prospector** [comment]
I do actually have plans to add an update checker at some point, and it will likely be Modrinth exclusive.

**Comment by Felix14-v2** [comment]
> My proposal has been implemented in ModUpdater

There is another mod, even better than ModUpdater – [ModManager](https://modrinth.com/mod/modmanager) [(GitHub)](https://github.com/DeathsGun/ModManager)
