### ISSUE TITLE
[Suggestion] Posibility to disable config entry based on the state of another config entry. 

### ISSUE THREAD

**Issue by Bulldog83** [Prospector/ModMenu#88]
Hello. I want to add a config entry dependent on the state of another entry. It would be great if it were possible to disable the config entry based on the state of another entry.

**Comment by Prospector** [comment]
Not sure what you mean by this? Could you explain more

**Comment by Bulldog83** [comment]
Ok. For example. I created 2 config entry. First is a boolean, the second is an integer slider. If the boolean entry is false, the second will going to disabled state.

**Comment by Prospector** [comment]
Oh. Mod menu doesn't add any configuration UI, so you're likely confusing it with something else. Perhaps Cloth Config?
