### ISSUE TITLE
Feature request: Animated Mod icons

### ISSUE THREAD

**Issue by Mhowser** [Prospector/ModMenu#93]
Allow mods to have animated icons / GIF support, and maybe a setting to toggle GIFs to animate or only display first frame (good default behavior). I think this will be a nice addition to add more flair and personality to user's mods.

**Comment by Prospector** [comment]
Hmm... need to decide on this one. The fabric spec doesn't say one way or another but it would be rather inconvenient to support animated gifs, plus it seems distracting. Currently I'm leaning towards no on this.

**Comment by Mhowser** [comment]
I asked if people want gif icons in the Fabric server and it looks like some people want it 
![image](https://user-images.githubusercontent.com/24195572/75603414-e3a96800-5a82-11ea-9999-1b6f3ab63643.png)

**Comment by Prospector** [comment]
I'm thinking no on this for now, unless it's added to the fabric spec that it's explicity valid. Plus to keep parity with resource and data pack icons.
